// examples/react/ColorValidator.tsx
/**
 * Momoto Engine — React: ColorValidator Component
 * Real-time WCAG + APCA validation with WASM engine
 */
import { useState, useEffect, useCallback } from 'react';
import init, {
  Color, wcagContrastRatio, wcagPasses, wcagLevel, apcaContrast,
  simulateCVD, cvdDeltaE
} from 'momoto-wasm';

// ── Types ─────────────────────────────────────────────────────────────────
interface ValidationResult {
  wcag: { ratio: number; level: string; passesAA: boolean; passesAAA: boolean };
  apca: { lc: number; passesBody: boolean; passesHeading: boolean };
  cvd: Array<{ type: string; simulated: string; deltaE: number; severity: string }>;
}

// ── WASM singleton init ───────────────────────────────────────────────────
let wasmReady = false;
const wasmInit = init().then(() => { wasmReady = true; });

function validate(fg: string, bg: string): ValidationResult | null {
  if (!wasmReady || !/^#[0-9a-f]{6}$/i.test(fg) || !/^#[0-9a-f]{6}$/i.test(bg)) return null;
  const fgC = Color.fromHex(fg);
  const bgC = Color.fromHex(bg);
  const ratio = wcagContrastRatio(fgC, bgC);
  const lc    = Math.abs(apcaContrast(fgC, bgC));
  const cvd   = (['protanopia', 'deuteranopia', 'tritanopia'] as const).map(type => {
    const sim = simulateCVD(fg, type);
    const de  = cvdDeltaE(fg, type);
    return { type, simulated: sim, deltaE: de, severity: de < 20 ? 'mild' : de < 60 ? 'moderate' : 'severe' };
  });
  return {
    wcag: { ratio, level: wcagLevel(ratio, false), passesAA: wcagPasses(ratio, 0, false), passesAAA: wcagPasses(ratio, 1, false) },
    apca: { lc, passesBody: lc >= 75, passesHeading: lc >= 60 },
    cvd
  };
}

// ── Component ─────────────────────────────────────────────────────────────
export function ColorValidator() {
  const [fg, setFg] = useState('#c8d4ff');
  const [bg, setBg] = useState('#07070e');
  const [result, setResult] = useState<ValidationResult | null>(null);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    wasmInit.then(() => {
      setReady(true);
      setResult(validate(fg, bg));
    });
  }, []);

  const handleChange = useCallback((newFg: string, newBg: string) => {
    setFg(newFg); setBg(newBg);
    setResult(validate(newFg, newBg));
  }, []);

  if (!ready) return <div style={styles.loading}>Loading WASM engine…</div>;

  return (
    <div style={styles.container}>
      <h2 style={styles.title}>Color Validator</h2>

      {/* Color pickers */}
      <div style={styles.row}>
        <label style={styles.label}>
          Foreground
          <div style={styles.pickerRow}>
            <input type="color" value={fg} onChange={e => handleChange(e.target.value, bg)} />
            <input type="text"  value={fg} onChange={e => handleChange(e.target.value, bg)}
                   style={styles.hexInput} maxLength={7} />
          </div>
        </label>
        <label style={styles.label}>
          Background
          <div style={styles.pickerRow}>
            <input type="color" value={bg} onChange={e => handleChange(fg, e.target.value)} />
            <input type="text"  value={bg} onChange={e => handleChange(fg, e.target.value)}
                   style={styles.hexInput} maxLength={7} />
          </div>
        </label>
        {/* Preview */}
        <div style={{ ...styles.preview, background: bg, color: fg }}>
          Aa — Sample Text
        </div>
      </div>

      {result && (
        <>
          {/* WCAG */}
          <section style={styles.section}>
            <h3>WCAG 2.1 — {result.wcag.ratio.toFixed(2)}:1</h3>
            <Badge ok={result.wcag.passesAA}  label="AA (4.5:1)" />
            <Badge ok={result.wcag.passesAAA} label="AAA (7:1)" />
            <span style={styles.levelBadge}>{result.wcag.level}</span>
          </section>

          {/* APCA */}
          <section style={styles.section}>
            <h3>APCA-W3 — {result.apca.lc.toFixed(1)} Lc</h3>
            <Badge ok={result.apca.passesBody}    label="Body text (≥75 Lc)" />
            <Badge ok={result.apca.passesHeading} label="Heading (≥60 Lc)" />
          </section>

          {/* CVD */}
          <section style={styles.section}>
            <h3>CVD Simulation (Viénot 1999)</h3>
            <div style={styles.cvdRow}>
              <Swatch color={fg} label="Original" />
              {result.cvd.map(({ type, simulated, severity }) => (
                <Swatch key={type} color={simulated}
                  label={`${type.replace('anopia','')}: ${severity}`} />
              ))}
            </div>
          </section>
        </>
      )}
    </div>
  );
}

// ── Sub-components ────────────────────────────────────────────────────────
function Badge({ ok, label }: { ok: boolean; label: string }) {
  return (
    <span style={{ ...styles.badge, background: ok ? '#166534' : '#7f1d1d',
                   color: ok ? '#4ade80' : '#f87171' }}>
      {ok ? '✓' : '✗'} {label}
    </span>
  );
}

function Swatch({ color, label }: { color: string; label: string }) {
  return (
    <div style={styles.swatch}>
      <div style={{ background: color, width: 48, height: 48, borderRadius: 8 }} />
      <span style={styles.swatchLabel}>{color}</span>
      <span style={styles.swatchLabel}>{label}</span>
    </div>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────
const styles = {
  container:   { fontFamily: 'system-ui', maxWidth: 600, margin: '0 auto', padding: 24, background: '#0f0f1a', color: '#e8eaf6', borderRadius: 16 },
  title:       { fontSize: 20, fontWeight: 700, color: '#a78bfa', marginBottom: 20 },
  row:         { display: 'flex', gap: 16, alignItems: 'center', marginBottom: 20, flexWrap: 'wrap' as const },
  label:       { display: 'flex', flexDirection: 'column' as const, gap: 8, fontSize: 13, color: '#94a3b8' },
  pickerRow:   { display: 'flex', gap: 8, alignItems: 'center' },
  hexInput:    { width: 80, background: '#1e1e2e', border: '1px solid #334155', borderRadius: 6, padding: '4px 8px', color: '#e8eaf6', fontFamily: 'monospace', fontSize: 13 },
  preview:     { padding: '12px 24px', borderRadius: 10, fontSize: 18, fontWeight: 600, border: '1px solid rgba(255,255,255,0.1)' },
  section:     { marginBottom: 20, borderTop: '1px solid #1e293b', paddingTop: 16 },
  badge:       { display: 'inline-block', borderRadius: 6, padding: '4px 10px', fontSize: 12, fontWeight: 600, marginRight: 8 },
  levelBadge:  { fontSize: 13, color: '#94a3b8' },
  cvdRow:      { display: 'flex', gap: 16, flexWrap: 'wrap' as const },
  swatch:      { display: 'flex', flexDirection: 'column' as const, alignItems: 'center', gap: 4 },
  swatchLabel: { fontSize: 11, color: '#94a3b8' },
  loading:     { padding: 24, color: '#94a3b8' },
} as const;

// examples/vue/ColorValidator.vue
<script setup lang="ts">
/**
 * Momoto Engine — Vue 3: ColorValidator Component
 * Composition API + WASM engine integration
 */
import { ref, computed, onMounted, watchEffect } from 'vue'

// ── WASM lazy init ────────────────────────────────────────────────────────
let wasmMod: Awaited<typeof import('momoto-wasm')> | null = null
const wasmReady = ref(false)

async function ensureWasm() {
  if (wasmMod) return
  const mod = await import('momoto-wasm')
  await mod.default()
  wasmMod = mod
  wasmReady.value = true
}

// ── State ─────────────────────────────────────────────────────────────────
const fg = ref('#c8d4ff')
const bg = ref('#07070e')
const validHex = (h: string) => /^#[0-9a-f]{6}$/i.test(h)

// ── Computed validation ───────────────────────────────────────────────────
const result = computed(() => {
  if (!wasmReady.value || !wasmMod) return null
  if (!validHex(fg.value) || !validHex(bg.value)) return null
  const w = wasmMod
  const fgC = w.Color.fromHex(fg.value)
  const bgC = w.Color.fromHex(bg.value)
  const ratio = w.wcagContrastRatio(fgC, bgC)
  const lc    = Math.abs(w.apcaContrast(fgC, bgC))
  return {
    ratio:         ratio.toFixed(2),
    level:         w.wcagLevel(ratio, false),
    passesAA:      w.wcagPasses(ratio, 0, false),
    passesAAA:     w.wcagPasses(ratio, 1, false),
    apcaLc:        lc.toFixed(1),
    passesBody:    lc >= 75,
    passesHeading: lc >= 60,
    cvd: (['protanopia', 'deuteranopia', 'tritanopia'] as const).map(type => ({
      type,
      simulated: w.simulateCVD(fg.value, type),
      deltaE:    w.cvdDeltaE(fg.value, type).toFixed(1),
    })),
  }
})

const previewStyle = computed(() => ({
  background: bg.value,
  color: fg.value,
  padding: '12px 20px',
  borderRadius: '10px',
  fontWeight: 600,
  fontSize: '18px',
  border: '1px solid rgba(255,255,255,0.1)',
}))

onMounted(ensureWasm)
</script>

<template>
  <div class="validator">
    <h2 class="heading">Color Validator</h2>

    <!-- Loading -->
    <p v-if="!wasmReady" class="loading">Loading WASM engine…</p>

    <template v-else>
      <!-- Controls -->
      <div class="controls">
        <label class="field">
          Foreground
          <div class="picker-row">
            <input type="color" v-model="fg" />
            <input type="text" v-model="fg" maxlength="7" class="hex-input" />
          </div>
        </label>
        <label class="field">
          Background
          <div class="picker-row">
            <input type="color" v-model="bg" />
            <input type="text" v-model="bg" maxlength="7" class="hex-input" />
          </div>
        </label>
        <div :style="previewStyle">Aa — Preview</div>
      </div>

      <!-- Results -->
      <template v-if="result">
        <!-- WCAG -->
        <section class="section">
          <h3>WCAG 2.1 — {{ result.ratio }}:1</h3>
          <span :class="['badge', result.passesAA ? 'pass' : 'fail']">
            {{ result.passesAA ? '✓' : '✗' }} AA (4.5:1)
          </span>
          <span :class="['badge', result.passesAAA ? 'pass' : 'fail']">
            {{ result.passesAAA ? '✓' : '✗' }} AAA (7:1)
          </span>
          <span class="level-tag">{{ result.level }}</span>
        </section>

        <!-- APCA -->
        <section class="section">
          <h3>APCA-W3 — {{ result.apcaLc }} Lc</h3>
          <span :class="['badge', result.passesBody ? 'pass' : 'fail']">
            {{ result.passesBody ? '✓' : '✗' }} Body (≥75 Lc)
          </span>
          <span :class="['badge', result.passesHeading ? 'pass' : 'fail']">
            {{ result.passesHeading ? '✓' : '✗' }} Heading (≥60 Lc)
          </span>
        </section>

        <!-- CVD -->
        <section class="section">
          <h3>CVD Simulation</h3>
          <div class="cvd-row">
            <div class="swatch-item">
              <div class="swatch" :style="{ background: fg }" />
              <span class="swatch-label">Original</span>
            </div>
            <div v-for="item in result.cvd" :key="item.type" class="swatch-item">
              <div class="swatch" :style="{ background: item.simulated }" />
              <span class="swatch-label">{{ item.type }}</span>
              <span class="swatch-de">ΔE {{ item.deltaE }}</span>
            </div>
          </div>
        </section>
      </template>
    </template>
  </div>
</template>

<style scoped>
.validator { font-family: system-ui; max-width: 600px; margin: 0 auto; padding: 24px;
             background: #0f0f1a; color: #e8eaf6; border-radius: 16px; }
.heading   { color: #a78bfa; margin-bottom: 20px; }
.loading   { color: #94a3b8; }
.controls  { display: flex; gap: 16px; align-items: center; margin-bottom: 20px; flex-wrap: wrap; }
.field     { display: flex; flex-direction: column; gap: 8px; font-size: 13px; color: #94a3b8; }
.picker-row{ display: flex; gap: 8px; align-items: center; }
.hex-input { width: 80px; background: #1e1e2e; border: 1px solid #334155; border-radius: 6px;
             padding: 4px 8px; color: #e8eaf6; font-family: monospace; font-size: 13px; }
.section   { margin-bottom: 20px; border-top: 1px solid #1e293b; padding-top: 16px; }
.section h3{ font-size: 14px; font-weight: 600; color: #c4b5fd; margin-bottom: 10px; }
.badge     { display: inline-block; border-radius: 6px; padding: 4px 10px;
             font-size: 12px; font-weight: 600; margin-right: 8px; }
.pass      { background: #166534; color: #4ade80; }
.fail      { background: #7f1d1d; color: #f87171; }
.level-tag { font-size: 13px; color: #94a3b8; }
.cvd-row   { display: flex; gap: 16px; flex-wrap: wrap; }
.swatch-item{ display: flex; flex-direction: column; align-items: center; gap: 4px; }
.swatch    { width: 48px; height: 48px; border-radius: 8px; }
.swatch-label{ font-size: 11px; color: #94a3b8; }
.swatch-de { font-size: 11px; color: #64748b; }
</style>
