// src/adapters/angular/button/index.ts
/**
 * @fileoverview Angular Button Adapter - Exports
 *
 * FASE 13: Multi-Framework Adapters
 *
 * Central export point for Angular Button components.
 *
 * @module momoto-ui/adapters/angular/button
 * @version 1.0.0
 */

// ============================================================================
// COMPONENTS
// ============================================================================

export { ButtonComponent } from './button.component';
export { ButtonWithVariantComponent, TOKEN_THEME } from './button-with-variant.component';

// ============================================================================
// MODULE
// ============================================================================

export { MomotoButtonModule } from './button.module';

// ============================================================================
// TYPES
// ============================================================================

export type {
  ButtonInputs,
  ButtonWithVariantInputs,
} from './types';

/**
 * USAGE EXAMPLES:
 *
 * # Example 1: Standalone component with explicit tokens
 * ```ts
 * import { Component } from '@angular/core';
 * import { ButtonComponent } from '@momoto/ui-adapters/angular/button';
 *
 * @Component({
 *   selector: 'app-my-component',
 *   standalone: true,
 *   imports: [ButtonComponent],
 *   template: `
 *     <momoto-button
 *       label="Submit"
 *       [backgroundColor]="primaryBg"
 *       [textColor]="primaryText"
 *       (buttonClick)="handleClick()"
 *     ></momoto-button>
 *   `
 * })
 * export class MyComponent {
 *   primaryBg = submitBackgroundToken;
 *   primaryText = submitTextToken;
 *
 *   handleClick() {
 *     console.log('Clicked!');
 *   }
 * }
 * ```
 *
 * # Example 2: ButtonWithVariant (preferred)
 * ```ts
 * import { Component } from '@angular/core';
 * import { ButtonWithVariantComponent, TOKEN_THEME } from '@momoto/ui-adapters/angular/button';
 *
 * @Component({
 *   selector: 'app-my-component',
 *   standalone: true,
 *   imports: [ButtonWithVariantComponent],
 *   providers: [
 *     { provide: TOKEN_THEME, useValue: myGeneratedTheme }
 *   ],
 *   template: `
 *     <momoto-button-with-variant
 *       label="Submit"
 *       variant="primary"
 *       (buttonClick)="handleSubmit()"
 *     ></momoto-button-with-variant>
 *   `
 * })
 * export class MyComponent {
 *   handleSubmit() {
 *     console.log('Submitted!');
 *   }
 * }
 * ```
 *
 * # Example 3: With module (older Angular)
 * ```ts
 * import { NgModule } from '@angular/core';
 * import { MomotoButtonModule, TOKEN_THEME } from '@momoto/ui-adapters/angular/button';
 *
 * @NgModule({
 *   imports: [MomotoButtonModule],
 *   providers: [
 *     { provide: TOKEN_THEME, useValue: myGeneratedTheme }
 *   ]
 * })
 * export class AppModule {}
 * ```
 *
 * # Example 4: Loading state
 * ```ts
 * import { Component } from '@angular/core';
 * import { ButtonWithVariantComponent } from '@momoto/ui-adapters/angular/button';
 *
 * @Component({
 *   selector: 'app-my-component',
 *   standalone: true,
 *   imports: [ButtonWithVariantComponent],
 *   template: `
 *     <momoto-button-with-variant
 *       label="Submit"
 *       variant="primary"
 *       [loading]="isLoading"
 *       (buttonClick)="handleSubmit()"
 *     ></momoto-button-with-variant>
 *   `
 * })
 * export class MyComponent {
 *   isLoading = false;
 *
 *   async handleSubmit() {
 *     this.isLoading = true;
 *     await this.submitForm();
 *     this.isLoading = false;
 *   }
 *
 *   async submitForm() {
 *     // Submit logic
 *   }
 * }
 * ```
 */

// src/adapters/react/button/index.ts
/**
 * @fileoverview React Button Adapter - Exports
 *
 * FASE 14: Core Consolidation
 *
 * Central export point for React Button components (refactored to use ButtonCore).
 *
 * @module momoto-ui/adapters/react/button
 * @version 2.0.0 (FASE 14)
 */

// ============================================================================
// COMPONENTS
// ============================================================================

export { Button, default } from './Button';
export { ButtonWithVariant } from './ButtonWithVariant';

// ============================================================================
// TYPES
// ============================================================================

export type {
  ButtonProps,
  ButtonVariantProps,
} from './types';

/**
 * USAGE EXAMPLES:
 *
 * # Example 1: Button with explicit tokens
 * ```tsx
 * import { Button } from '@momoto/ui-adapters/react/button';
 *
 * function MyComponent() {
 *   const primaryBg = submitBackgroundToken;
 *   const primaryText = submitTextToken;
 *
 *   const handleClick = () => {
 *     console.log('Clicked!');
 *   };
 *
 *   return (
 *     <Button
 *       label="Submit"
 *       backgroundColor={primaryBg}
 *       textColor={primaryText}
 *       onClick={handleClick}
 *     />
 *   );
 * }
 * ```
 *
 * # Example 2: ButtonWithVariant (preferred)
 * ```tsx
 * import { ButtonWithVariant } from '@momoto/ui-adapters/react/button';
 *
 * function MyComponent() {
 *   const handleClick = () => {
 *     console.log('Clicked!');
 *   };
 *
 *   return (
 *     <ButtonWithVariant
 *       label="Submit"
 *       variant="primary"
 *       onClick={handleClick}
 *     />
 *   );
 * }
 * ```
 *
 * # Example 3: With icon
 * ```tsx
 * import { ButtonWithVariant } from '@momoto/ui-adapters/react/button';
 * import { IconCheck } from './icons';
 *
 * function MyComponent() {
 *   return (
 *     <ButtonWithVariant
 *       label="Save"
 *       variant="primary"
 *       icon={<IconCheck />}
 *       iconPosition="left"
 *       onClick={handleSave}
 *     />
 *   );
 * }
 * ```
 *
 * # Example 4: Loading state
 * ```tsx
 * import { ButtonWithVariant } from '@momoto/ui-adapters/react/button';
 * import { useState } from 'react';
 *
 * function MyComponent() {
 *   const [isLoading, setIsLoading] = useState(false);
 *
 *   const handleSubmit = async () => {
 *     setIsLoading(true);
 *     await submitForm();
 *     setIsLoading(false);
 *   };
 *
 *   return (
 *     <ButtonWithVariant
 *       label="Submit"
 *       variant="primary"
 *       loading={isLoading}
 *       onClick={handleSubmit}
 *     />
 *   );
 * }
 * ```
 *
 * MIGRATION FROM FASE 11:
 * ```tsx
 * // Old import (FASE 11)
 * import { Button, ButtonWithVariant } from '@zuclubit/momoto-ui/components/primitives/Button';
 *
 * // New import (FASE 14)
 * import { Button, ButtonWithVariant } from '@momoto/ui-adapters/react/button';
 *
 * // Usage is IDENTICAL - no breaking changes
 * <ButtonWithVariant label="Submit" variant="primary" onClick={handleClick} />
 * ```
 */
