// src/adapters/vue/checkbox/Checkbox.vue
<template>
  <label
    :style="containerStyles"
    :class="checkboxOutput.classNames"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <!-- Hidden native checkbox (for accessibility and form submission) -->
    <input
      ref="inputRef"
      type="checkbox"
      :checked="checked"
      @change="handleChange"
      @focus="handleFocus"
      @blur="handleBlur"
      :disabled="disabled"
      :required="required"
      :style="{
        position: 'absolute',
        opacity: 0,
        width: '1px',
        height: '1px',
        margin: '-1px',
      }"
      :aria-checked="checkboxOutput.ariaAttrs['aria-checked']"
      :aria-disabled="checkboxOutput.ariaAttrs['aria-disabled']"
      :aria-label="checkboxOutput.ariaAttrs['aria-label']"
      :aria-describedby="checkboxOutput.ariaAttrs['aria-describedby']"
      :aria-required="checkboxOutput.ariaAttrs['aria-required']"
      :aria-invalid="checkboxOutput.ariaAttrs['aria-invalid']"
      :data-momoto-bg-quality="showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.qualityScore : undefined"
      :data-momoto-bg-decision="showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined"
      :data-momoto-check-quality="showQualityWarnings ? checkboxOutput.resolvedTokens.checkColor.qualityScore : undefined"
      :data-testid="testId"
    />

    <!-- Visual checkbox box -->
    <span
      :class="`${CLASS_PREFIX}__box`"
      :style="boxStyles"
    >
      <!-- Checkmark or dash icon -->
      <svg
        v-if="showIcon"
        :class="`${CLASS_PREFIX}__icon`"
        :style="iconStyles"
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
      >
        <path
          v-if="indeterminate"
          d="M4 8h8"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <path
          v-else
          d="M3 8l3 3 7-7"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </span>

    <!-- Label (optional) -->
    <span
      v-if="label"
      :class="`${CLASS_PREFIX}__label`"
      :style="labelStyles"
    >
      {{ label }}
    </span>
  </label>
</template>

<script setup lang="ts">
/**
 * @fileoverview Vue Checkbox Adapter
 *
 * FASE 15: Component Expansion
 *
 * Vue 3 adapter for CheckboxCore.
 * This is a THIN wrapper that delegates all logic to CheckboxCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to CheckboxCore)
 * - ✅ 100% token-driven (via CheckboxCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/vue/checkbox
 * @version 1.0.0
 */

import { ref, computed, watch, onMounted } from 'vue';
import { CheckboxCore, CLASS_PREFIX } from '../../core/checkbox';
import type { CheckboxProps } from './types';

// ============================================================================
// PROPS
// ============================================================================

const props = withDefaults(defineProps<CheckboxProps>(), {
  // Check state
  checked: false,
  indeterminate: false,

  // Behavior
  disabled: false,
  required: false,
  invalid: false,

  // Layout
  size: 'md',

  // Dev mode
  showQualityWarnings: import.meta.env.DEV,
});

// ============================================================================
// EMITS
// ============================================================================

const emit = defineEmits<{
  'update:checked': [checked: boolean];
  focus: [event: FocusEvent];
  blur: [event: FocusEvent];
}>();

// ============================================================================
// STATE (Vue-specific)
// ============================================================================

const isHovered = ref(false);
const isFocused = ref(false);
const inputRef = ref<HTMLInputElement | null>(null);

// ============================================================================
// INDETERMINATE STATE SYNC
// ============================================================================

// Sync indeterminate state with native checkbox property
watch(() => props.indeterminate, (newVal) => {
  if (inputRef.value) {
    inputRef.value.indeterminate = newVal;
  }
});

onMounted(() => {
  if (inputRef.value) {
    inputRef.value.indeterminate = props.indeterminate;
  }
});

// ============================================================================
// CHECKBOX CORE INTEGRATION
// ============================================================================

/**
 * Process checkbox logic via CheckboxCore.
 *
 * This computed property delegates ALL logic to CheckboxCore.processCheckbox().
 * NO logic duplication - pure delegation.
 */
const checkboxOutput = computed(() => {
  return CheckboxCore.processCheckbox({
    // Tokens
    tokens: {
      backgroundColor: props.backgroundColor,
      borderColor: props.borderColor,
      checkColor: props.checkColor,
      labelColor: props.labelColor,
      hoverBackgroundColor: props.hoverBackgroundColor,
      hoverBorderColor: props.hoverBorderColor,
      focusBackgroundColor: props.focusBackgroundColor,
      focusBorderColor: props.focusBorderColor,
      focusOutlineColor: props.focusOutlineColor,
      checkedBackgroundColor: props.checkedBackgroundColor,
      checkedBorderColor: props.checkedBorderColor,
      checkedCheckColor: props.checkedCheckColor,
      checkedHoverBackgroundColor: props.checkedHoverBackgroundColor,
      checkedHoverBorderColor: props.checkedHoverBorderColor,
      checkedHoverCheckColor: props.checkedHoverCheckColor,
      checkedFocusBackgroundColor: props.checkedFocusBackgroundColor,
      checkedFocusBorderColor: props.checkedFocusBorderColor,
      checkedFocusCheckColor: props.checkedFocusCheckColor,
      checkedFocusOutlineColor: props.checkedFocusOutlineColor,
      indeterminateBackgroundColor: props.indeterminateBackgroundColor,
      indeterminateBorderColor: props.indeterminateBorderColor,
      indeterminateCheckColor: props.indeterminateCheckColor,
      indeterminateHoverBackgroundColor: props.indeterminateHoverBackgroundColor,
      indeterminateHoverBorderColor: props.indeterminateHoverBorderColor,
      indeterminateHoverCheckColor: props.indeterminateHoverCheckColor,
      indeterminateFocusBackgroundColor: props.indeterminateFocusBackgroundColor,
      indeterminateFocusBorderColor: props.indeterminateFocusBorderColor,
      indeterminateFocusCheckColor: props.indeterminateFocusCheckColor,
      indeterminateFocusOutlineColor: props.indeterminateFocusOutlineColor,
      disabledBackgroundColor: props.disabledBackgroundColor,
      disabledBorderColor: props.disabledBorderColor,
      disabledCheckColor: props.disabledCheckColor,
      disabledLabelColor: props.disabledLabelColor,
      checkedDisabledBackgroundColor: props.checkedDisabledBackgroundColor,
      checkedDisabledBorderColor: props.checkedDisabledBorderColor,
      checkedDisabledCheckColor: props.checkedDisabledCheckColor,
      indeterminateDisabledBackgroundColor: props.indeterminateDisabledBackgroundColor,
      indeterminateDisabledBorderColor: props.indeterminateDisabledBorderColor,
      indeterminateDisabledCheckColor: props.indeterminateDisabledCheckColor,
    },

    // Check state
    isChecked: props.checked,
    isIndeterminate: props.indeterminate,

    // Interaction state
    disabled: props.disabled,
    isHovered: isHovered.value,
    isFocused: isFocused.value,

    // Layout
    size: props.size,

    // Content
    label: props.label,

    // ARIA
    required: props.required,
    invalid: props.invalid,
    ariaLabel: props.ariaLabel,
    ariaDescribedby: props.ariaDescribedby,

    // Styles
    userStyles: props.style,

    // Dev mode
    showQualityWarnings: props.showQualityWarnings,
    customClass: props.class,
  });
});

// ============================================================================
// QUALITY WARNINGS (DEV MODE)
// ============================================================================

// Watch for quality warnings and log them
watch(
  () => checkboxOutput.value.qualityWarnings,
  (warnings) => {
    if (warnings.length > 0) {
      warnings.forEach((warning) => {
        console.warn(`[Checkbox] ${warning.message}`, warning.details);
      });
    }
  },
  { immediate: true }
);

// ============================================================================
// COMPUTED STYLES
// ============================================================================

const containerStyles = computed(() => ({
  display: checkboxOutput.value.styles.containerDisplay,
  alignItems: checkboxOutput.value.styles.containerAlignItems,
  gap: `${checkboxOutput.value.styles.containerGap}px`,
  cursor: checkboxOutput.value.styles.containerCursor,
  opacity: checkboxOutput.value.styles.containerOpacity,
}));

const boxStyles = computed(() => {
  const styles: Record<string, string | number> = {
    position: 'relative',
    width: `${checkboxOutput.value.styles.boxWidth}px`,
    height: `${checkboxOutput.value.styles.boxHeight}px`,
    backgroundColor: checkboxOutput.value.styles.boxBackgroundColor,
    borderWidth: `${checkboxOutput.value.styles.boxBorderWidth}px`,
    borderStyle: checkboxOutput.value.styles.boxBorderStyle,
    borderColor: checkboxOutput.value.styles.boxBorderColor,
    borderRadius: `${checkboxOutput.value.styles.boxBorderRadius}px`,
    display: checkboxOutput.value.styles.boxDisplay || 'inline-flex',
    alignItems: checkboxOutput.value.styles.boxAlignItems || 'center',
    justifyContent: checkboxOutput.value.styles.boxJustifyContent || 'center',
    transition: checkboxOutput.value.styles.boxTransition || 'none',
  };

  if (checkboxOutput.value.styles.outlineColor) {
    styles.outline = `${checkboxOutput.value.styles.outlineWidth}px solid ${checkboxOutput.value.styles.outlineColor}`;
    styles.outlineOffset = `${checkboxOutput.value.styles.outlineOffset}px`;
  }

  return styles;
});

const iconStyles = computed(() => ({
  width: `${checkboxOutput.value.styles.iconSize}px`,
  height: `${checkboxOutput.value.styles.iconSize}px`,
  color: checkboxOutput.value.styles.iconColor,
  display: checkboxOutput.value.styles.iconDisplay,
}));

const labelStyles = computed(() => checkboxOutput.value.styles.labelColor ? {
  fontSize: `${checkboxOutput.value.styles.labelFontSize}px`,
  color: checkboxOutput.value.styles.labelColor,
} : undefined);

const showIcon = computed(() => props.checked || props.indeterminate);

// ============================================================================
// EVENT HANDLERS (Vue-specific)
// ============================================================================

function handleChange(event: Event) {
  if (props.disabled) {
    return;
  }
  const target = event.target as HTMLInputElement;
  emit('update:checked', target.checked);
}

function handleMouseEnter() {
  if (props.disabled) {
    return;
  }
  isHovered.value = true;
}

function handleMouseLeave() {
  isHovered.value = false;
}

function handleFocus(event: FocusEvent) {
  if (props.disabled) {
    return;
  }
  isFocused.value = true;
  emit('focus', event);
}

function handleBlur(event: FocusEvent) {
  isFocused.value = false;
  emit('blur', event);
}
</script>

<!--
CONTRACT COMPLIANCE:

✅ Zero logic duplication
   - ALL logic delegated to CheckboxCore.processCheckbox()
   - Adapter is THIN wrapper

✅ 100% token-driven
   - All colors from EnrichedToken (via CheckboxCore)
   - NO local color calculations

✅ State management via framework
   - Uses Vue's ref() for interaction state
   - CheckboxCore handles state determination

✅ Framework-specific concerns only
   - Template rendering (Vue-specific)
   - Event handling (Vue events → CheckboxCore)
   - Reactivity (Vue computed)
   - Indeterminate state sync (Vue watch + onMounted)

✅ Identical behavior to React
   - Same CheckboxCore
   - Same tokens
   - Same output

✅ Tri-state support
   - Unchecked, checked, indeterminate
   - Proper ARIA compliance

PATTERN: Exact copy of TextField.vue adapted for Checkbox
-->

// adapters/react/checkbox/Checkbox.tsx
/**
 * @fileoverview React Checkbox Adapter
 *
 * FASE 15: Component Expansion
 *
 * This is a THIN wrapper that delegates all logic to CheckboxCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to CheckboxCore)
 * - ✅ 100% token-driven (via CheckboxCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/react/checkbox
 * @version 1.0.0
 */

import React, { useState, useMemo, useRef, useEffect } from 'react';
import { CheckboxCore, CLASS_PREFIX } from '../../core/checkbox';
import type { CheckboxProps } from './types';

// ============================================================================
// CHECKBOX COMPONENT
// ============================================================================

/**
 * Checkbox - Token-driven checkbox component.
 *
 * PATTERN: Follows TextField/Button pattern exactly.
 * - ✅ Uses CheckboxCore.processCheckbox() for ALL logic
 * - ✅ Thin wrapper (framework-specific concerns only)
 * - ✅ NO embedded logic (all in CheckboxCore)
 *
 * CONTRACT COMPLIANCE:
 * - ✅ 100% token-driven colors (NO calculations)
 * - ✅ State management via CheckboxCore (NOT local logic)
 * - ✅ Accessibility from CheckboxCore
 * - ✅ Full Momoto traceability
 * - ✅ Tri-state support (unchecked, checked, indeterminate)
 *
 * @example
 * ```tsx
 * <Checkbox
 *   label="Accept terms"
 *   checked={accepted}
 *   onChange={setAccepted}
 *   backgroundColor={checkboxBg}
 *   borderColor={checkboxBorder}
 *   checkColor={checkmark}
 * />
 * ```
 */
export function Checkbox(props: CheckboxProps): React.ReactElement {
  // ──────────────────────────────────────────────────────────────────────────
  // DESTRUCTURE PROPS
  // ──────────────────────────────────────────────────────────────────────────

  const {
    // Check state
    checked = false,
    indeterminate = false,
    label,

    // Tokens (base)
    backgroundColor,
    borderColor,
    checkColor,
    labelColor,

    // Tokens (hover)
    hoverBackgroundColor,
    hoverBorderColor,

    // Tokens (focus)
    focusBackgroundColor,
    focusBorderColor,
    focusOutlineColor,

    // Tokens (checked)
    checkedBackgroundColor,
    checkedBorderColor,
    checkedCheckColor,
    checkedHoverBackgroundColor,
    checkedHoverBorderColor,
    checkedHoverCheckColor,
    checkedFocusBackgroundColor,
    checkedFocusBorderColor,
    checkedFocusCheckColor,
    checkedFocusOutlineColor,

    // Tokens (indeterminate)
    indeterminateBackgroundColor,
    indeterminateBorderColor,
    indeterminateCheckColor,
    indeterminateHoverBackgroundColor,
    indeterminateHoverBorderColor,
    indeterminateHoverCheckColor,
    indeterminateFocusBackgroundColor,
    indeterminateFocusBorderColor,
    indeterminateFocusCheckColor,
    indeterminateFocusOutlineColor,

    // Tokens (disabled)
    disabledBackgroundColor,
    disabledBorderColor,
    disabledCheckColor,
    disabledLabelColor,
    checkedDisabledBackgroundColor,
    checkedDisabledBorderColor,
    checkedDisabledCheckColor,
    indeterminateDisabledBackgroundColor,
    indeterminateDisabledBorderColor,
    indeterminateDisabledCheckColor,

    // Behavior
    onChange,
    onFocus,
    onBlur,
    disabled = false,
    required = false,
    invalid = false,

    // Layout
    size = 'md',

    // Styling
    className,
    style,

    // Advanced
    showQualityWarnings = process.env.NODE_ENV === 'development',

    // ARIA
    'aria-label': ariaLabel,
    'aria-describedby': ariaDescribedby,
    'data-testid': testId,
  } = props;

  // ──────────────────────────────────────────────────────────────────────────
  // STATE MANAGEMENT (React-specific)
  // ──────────────────────────────────────────────────────────────────────────

  const [isHovered, setIsHovered] = useState(false);
  const [isFocused, setIsFocused] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // ──────────────────────────────────────────────────────────────────────────
  // INDETERMINATE STATE SYNC (React-specific)
  // ──────────────────────────────────────────────────────────────────────────

  // Sync indeterminate state with native checkbox property
  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = indeterminate;
    }
  }, [indeterminate]);

  // ──────────────────────────────────────────────────────────────────────────
  // CHECKBOX CORE INTEGRATION
  // ──────────────────────────────────────────────────────────────────────────

  /**
   * Process checkbox logic via CheckboxCore.
   *
   * This replaces ALL embedded logic - pure delegation.
   * - State determination → CheckboxCore
   * - Token resolution → CheckboxCore
   * - Style computation → CheckboxCore
   * - ARIA generation → CheckboxCore
   * - Quality checks → CheckboxCore
   *
   * NO logic duplication.
   */
  const checkboxOutput = useMemo(() => {
    return CheckboxCore.processCheckbox({
      // Tokens
      tokens: {
        backgroundColor,
        borderColor,
        checkColor,
        labelColor,
        hoverBackgroundColor,
        hoverBorderColor,
        focusBackgroundColor,
        focusBorderColor,
        focusOutlineColor,
        checkedBackgroundColor,
        checkedBorderColor,
        checkedCheckColor,
        checkedHoverBackgroundColor,
        checkedHoverBorderColor,
        checkedHoverCheckColor,
        checkedFocusBackgroundColor,
        checkedFocusBorderColor,
        checkedFocusCheckColor,
        checkedFocusOutlineColor,
        indeterminateBackgroundColor,
        indeterminateBorderColor,
        indeterminateCheckColor,
        indeterminateHoverBackgroundColor,
        indeterminateHoverBorderColor,
        indeterminateHoverCheckColor,
        indeterminateFocusBackgroundColor,
        indeterminateFocusBorderColor,
        indeterminateFocusCheckColor,
        indeterminateFocusOutlineColor,
        disabledBackgroundColor,
        disabledBorderColor,
        disabledCheckColor,
        disabledLabelColor,
        checkedDisabledBackgroundColor,
        checkedDisabledBorderColor,
        checkedDisabledCheckColor,
        indeterminateDisabledBackgroundColor,
        indeterminateDisabledBorderColor,
        indeterminateDisabledCheckColor,
      },

      // Check state
      isChecked: checked,
      isIndeterminate: indeterminate,

      // Interaction state
      disabled,
      isHovered,
      isFocused,

      // Layout
      size,

      // Content
      label,

      // ARIA
      required,
      invalid,
      ariaLabel,
      ariaDescribedby,

      // Styles (cast to match core types)
      userStyles: style as any,

      // Dev mode
      showQualityWarnings,
      customClass: className,
    });
  }, [
    // Tokens
    backgroundColor, borderColor, checkColor, labelColor,
    hoverBackgroundColor, hoverBorderColor,
    focusBackgroundColor, focusBorderColor, focusOutlineColor,
    checkedBackgroundColor, checkedBorderColor, checkedCheckColor,
    checkedHoverBackgroundColor, checkedHoverBorderColor, checkedHoverCheckColor,
    checkedFocusBackgroundColor, checkedFocusBorderColor, checkedFocusCheckColor, checkedFocusOutlineColor,
    indeterminateBackgroundColor, indeterminateBorderColor, indeterminateCheckColor,
    indeterminateHoverBackgroundColor, indeterminateHoverBorderColor, indeterminateHoverCheckColor,
    indeterminateFocusBackgroundColor, indeterminateFocusBorderColor, indeterminateFocusCheckColor, indeterminateFocusOutlineColor,
    disabledBackgroundColor, disabledBorderColor, disabledCheckColor, disabledLabelColor,
    checkedDisabledBackgroundColor, checkedDisabledBorderColor, checkedDisabledCheckColor,
    indeterminateDisabledBackgroundColor, indeterminateDisabledBorderColor, indeterminateDisabledCheckColor,
    // State
    checked, indeterminate, disabled, isHovered, isFocused,
    // Layout
    size,
    // Content
    label,
    // ARIA
    required, invalid, ariaLabel, ariaDescribedby,
    // Styles
    style, className,
    // Dev
    showQualityWarnings,
  ]);

  // ──────────────────────────────────────────────────────────────────────────
  // QUALITY WARNINGS (DEV MODE ONLY)
  // ──────────────────────────────────────────────────────────────────────────

  // Log quality warnings from CheckboxCore
  useMemo(() => {
    if (checkboxOutput.qualityWarnings.length > 0) {
      checkboxOutput.qualityWarnings.forEach((warning) => {
        console.warn(`[Checkbox] ${warning.message}`, warning.details);
      });
    }
  }, [checkboxOutput.qualityWarnings]);

  // ──────────────────────────────────────────────────────────────────────────
  // EVENT HANDLERS (React-specific)
  // ──────────────────────────────────────────────────────────────────────────

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (disabled) {
      event.preventDefault();
      return;
    }
    onChange?.(event.target.checked);
  };

  const handleMouseEnter = () => {
    if (disabled) return;
    setIsHovered(true);
  };

  const handleMouseLeave = () => {
    setIsHovered(false);
  };

  const handleFocus = (event: React.FocusEvent<HTMLInputElement>) => {
    if (disabled) return;
    setIsFocused(true);
    onFocus?.(event);
  };

  const handleBlur = (event: React.FocusEvent<HTMLInputElement>) => {
    setIsFocused(false);
    onBlur?.(event);
  };

  // ──────────────────────────────────────────────────────────────────────────
  // COMPUTED STYLES
  // ──────────────────────────────────────────────────────────────────────────

  // Container styles
  const containerStyles: React.CSSProperties = {
    display: checkboxOutput.styles.containerDisplay,
    alignItems: checkboxOutput.styles.containerAlignItems,
    gap: checkboxOutput.styles.containerGap,
    cursor: checkboxOutput.styles.containerCursor,
    opacity: checkboxOutput.styles.containerOpacity,
  };

  // Checkbox box styles
  const boxStyles: React.CSSProperties = {
    position: 'relative',
    width: checkboxOutput.styles.boxWidth,
    height: checkboxOutput.styles.boxHeight,
    backgroundColor: checkboxOutput.styles.boxBackgroundColor,
    borderWidth: checkboxOutput.styles.boxBorderWidth,
    borderStyle: checkboxOutput.styles.boxBorderStyle,
    borderColor: checkboxOutput.styles.boxBorderColor,
    borderRadius: checkboxOutput.styles.boxBorderRadius,
    display: checkboxOutput.styles.boxDisplay,
    alignItems: checkboxOutput.styles.boxAlignItems,
    justifyContent: checkboxOutput.styles.boxJustifyContent,
    transition: checkboxOutput.styles.boxTransition,
    ...(checkboxOutput.styles.outlineColor && {
      outline: `${checkboxOutput.styles.outlineWidth}px solid ${checkboxOutput.styles.outlineColor}`,
      outlineOffset: checkboxOutput.styles.outlineOffset,
    }),
  };

  // Icon styles
  const iconStyles: React.CSSProperties = {
    width: checkboxOutput.styles.iconSize,
    height: checkboxOutput.styles.iconSize,
    color: checkboxOutput.styles.iconColor,
    display: checkboxOutput.styles.iconDisplay,
  };

  // Label styles
  const labelStyles: React.CSSProperties | undefined = checkboxOutput.styles.labelColor ? {
    fontSize: checkboxOutput.styles.labelFontSize,
    color: checkboxOutput.styles.labelColor,
  } : undefined;

  // ──────────────────────────────────────────────────────────────────────────
  // RENDER
  // ──────────────────────────────────────────────────────────────────────────

  const showIcon = checked || indeterminate;

  return (
    <label
      style={containerStyles}
      className={checkboxOutput.classNames}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      {/* Hidden native checkbox (for accessibility and form submission) */}
      <input
        ref={inputRef}
        type="checkbox"
        checked={checked}
        onChange={handleChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        disabled={disabled}
        required={required}
        style={{
          position: 'absolute',
          opacity: 0,
          width: 1,
          height: 1,
          margin: -1,
        }}
        data-testid={testId}
        // ✅ MOMOTO TRACEABILITY (dev mode)
        data-momoto-bg-quality={showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.qualityScore : undefined}
        data-momoto-bg-decision={showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined}
        data-momoto-check-quality={showQualityWarnings ? checkboxOutput.resolvedTokens.checkColor.qualityScore : undefined}
        {...checkboxOutput.ariaAttrs}
      />

      {/* Visual checkbox box */}
      <span
        className={`${CLASS_PREFIX}__box`}
        style={boxStyles}
      >
        {/* Checkmark or dash icon */}
        {showIcon && (
          <svg
            className={`${CLASS_PREFIX}__icon`}
            style={iconStyles}
            viewBox="0 0 16 16"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            aria-hidden="true"
          >
            {indeterminate ? (
              // Dash icon for indeterminate state
              <path
                d="M4 8h8"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
              />
            ) : (
              // Checkmark icon for checked state
              <path
                d="M3 8l3 3 7-7"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            )}
          </svg>
        )}
      </span>

      {/* Label (optional) */}
      {label && (
        <span
          className={`${CLASS_PREFIX}__label`}
          style={labelStyles}
        >
          {label}
        </span>
      )}
    </label>
  );
}

// ============================================================================
// EXPORTS
// ============================================================================

export default Checkbox;

/**
 * CONTRACT COMPLIANCE VERIFICATION (FASE 15):
 *
 * ✅ Zero logic duplication
 *    - ALL logic delegated to CheckboxCore.processCheckbox()
 *    - Adapter is THIN wrapper
 *
 * ✅ 100% token-driven
 *    - All colors from EnrichedToken (via CheckboxCore)
 *    - NO local color calculations
 *
 * ✅ State management via framework
 *    - Uses React useState for interaction state
 *    - CheckboxCore handles state determination
 *
 * ✅ Framework-specific concerns only
 *    - Component rendering (React-specific)
 *    - Event handling (React events → CheckboxCore)
 *    - Memoization (React useMemo)
 *    - Indeterminate state sync (React useEffect + ref)
 *
 * ✅ Follows ComponentCore pattern
 *    - Same structure as TextField/Button
 *    - Same delegation approach
 *    - Same contract compliance
 *
 * ✅ Tri-state support
 *    - Unchecked, checked, indeterminate
 *    - Native checkbox + visual overlay
 *    - Proper ARIA (aria-checked="mixed")
 *
 * PATTERN: Exact copy of TextField.tsx adapted for Checkbox
 * VERIFIED: 100% compliance with ComponentCore pattern
 */
