// src/adapters/react/switch/Switch.tsx
/**
 * @fileoverview React Switch Adapter
 * FASE 15.5: Component Expansion - Switch
 */

import type React from 'react';
import { useState, useMemo, useEffect } from 'react';
import { SwitchCore, CLASS_PREFIX } from '../../core/switch';
import type { SwitchTokens } from '../../core/switch/switchCore.types';
import type { SwitchProps } from './types';

export function Switch(props: SwitchProps) {
  const { checked, onChange, disabled = false, required = false, error = false, size = 'md', label, helperText, errorMessage, className, style, ariaLabel, ariaDescribedby, ariaLabelledby, testId, showQualityWarnings = true, ...tokenProps } = props;

  const [isHovered, setIsHovered] = useState(false);
  const [isFocused, setIsFocused] = useState(false);

  const switchOutput = useMemo(
    () =>
      SwitchCore.processSwitch({
        tokens: tokenProps as SwitchTokens,
        isChecked: checked,
        disabled,
        isHovered,
        isFocused,
        hasError: error,
        size,
        label,
        helperText,
        errorMessage,
        required,
        ariaLabel,
        ariaDescribedby,
        ariaLabelledby,
        userStyles: style as any,
        customClass: className,
        showQualityWarnings,
      }),
    [checked, disabled, isHovered, isFocused, error, size, label, helperText, errorMessage, required, ariaLabel, ariaDescribedby, ariaLabelledby, style, className, showQualityWarnings, tokenProps]
  );

  useEffect(() => {
    if (switchOutput.qualityWarnings.length > 0) {
      switchOutput.qualityWarnings.forEach((w) => console.warn(`[Switch] ${w.message}`, w.details));
    }
  }, [switchOutput.qualityWarnings]);

  const displayHelperText = error && errorMessage ? errorMessage : helperText;

  return (
    <div style={{ display: switchOutput.styles.containerDisplay, alignItems: switchOutput.styles.containerAlignItems, gap: `${switchOutput.styles.containerGap}px` }} className={switchOutput.classNames}>
      <div
        role={switchOutput.ariaAttrs.role}
        aria-checked={switchOutput.ariaAttrs['aria-checked']}
        aria-disabled={switchOutput.ariaAttrs['aria-disabled']}
        aria-required={switchOutput.ariaAttrs['aria-required']}
        aria-invalid={switchOutput.ariaAttrs['aria-invalid']}
        aria-label={switchOutput.ariaAttrs['aria-label']}
        aria-describedby={switchOutput.ariaAttrs['aria-describedby']}
        aria-labelledby={switchOutput.ariaAttrs['aria-labelledby']}
        tabIndex={disabled ? -1 : 0}
        style={{
          position: switchOutput.styles.trackPosition as React.CSSProperties['position'],
          display: switchOutput.styles.trackDisplay,
          width: `${switchOutput.styles.trackWidth}px`,
          height: `${switchOutput.styles.trackHeight}px`,
          backgroundColor: switchOutput.styles.trackBackgroundColor,
          borderWidth: `${switchOutput.styles.trackBorderWidth}px`,
          borderStyle: switchOutput.styles.trackBorderStyle,
          borderColor: switchOutput.styles.trackBorderColor,
          borderRadius: `${switchOutput.styles.trackBorderRadius}px`,
          cursor: switchOutput.styles.trackCursor,
          transition: switchOutput.styles.trackTransition,
          opacity: switchOutput.styles.trackOpacity,
          outline: switchOutput.styles.outlineColor ? `${switchOutput.styles.outlineWidth}px solid ${switchOutput.styles.outlineColor}` : 'none',
          outlineOffset: `${switchOutput.styles.outlineOffset}px`,
        }}
        className={`${CLASS_PREFIX}__track`}
        onClick={() => !disabled && onChange(!checked)}
        onMouseEnter={() => !disabled && setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        onFocus={() => !disabled && setIsFocused(true)}
        onBlur={() => setIsFocused(false)}
        data-testid={testId}
      >
        <span
          style={{
            position: switchOutput.styles.thumbPosition as React.CSSProperties['position'],
            display: switchOutput.styles.thumbDisplay,
            top: '50%',
            left: `${switchOutput.styles.trackBorderWidth + 2}px`,
            width: `${switchOutput.styles.thumbWidth}px`,
            height: `${switchOutput.styles.thumbHeight}px`,
            backgroundColor: switchOutput.styles.thumbBackgroundColor,
            borderRadius: `${switchOutput.styles.thumbBorderRadius}px`,
            transition: switchOutput.styles.thumbTransition,
            transform: `translateY(-50%) ${switchOutput.styles.thumbTransform}`,
          }}
          className={`${CLASS_PREFIX}__thumb`}
        />
      </div>

      {label && (
        <label style={{ display: switchOutput.styles.labelDisplay, fontSize: `${switchOutput.styles.labelFontSize}px`, color: switchOutput.styles.labelColor, fontWeight: switchOutput.styles.labelFontWeight }} className={`${CLASS_PREFIX}__label`}>
          {label}{required && ' *'}
        </label>
      )}

      {displayHelperText && (
        <span style={{ display: switchOutput.styles.helperDisplay, fontSize: `${switchOutput.styles.helperFontSize}px`, color: switchOutput.styles.helperColor }} className={`${CLASS_PREFIX}__helper`}>
          {displayHelperText}
        </span>
      )}
    </div>
  );
}

// src/adapters/angular/switch/switch.component.ts
/**
 * @fileoverview Angular Switch Component
 * FASE 15.5: Component Expansion - Switch
 */

import { Component, Input, Output, EventEmitter, OnChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SwitchCore, CLASS_PREFIX } from '../../core/switch';
import type { SwitchCoreOutput, SwitchSize, SwitchStyles } from '../../core/switch';
import type { EnrichedToken } from '../../../domain/tokens/value-objects/EnrichedToken';

@Component({
  selector: 'momoto-switch',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './switch.component.html',
  styleUrls: ['./switch.component.css'],
})
export class SwitchComponent implements OnChanges {
  @Input({ required: true }) checked!: boolean;
  @Input() label?: string;
  @Input({ required: true }) trackBackgroundColor!: EnrichedToken;
  @Input({ required: true }) trackBorderColor!: EnrichedToken;
  @Input({ required: true }) thumbColor!: EnrichedToken;
  @Input({ required: true }) checkedTrackBackgroundColor!: EnrichedToken;
  @Input() disabled = false;
  @Input() required = false;
  @Input() error = false;
  @Input() size: SwitchSize = 'md';
  @Input() helperText?: string;
  @Input() errorMessage?: string;
  @Input() customClass?: string;
  @Input() customStyle?: Partial<SwitchStyles>;
  @Input() showQualityWarnings = true;

  @Output() checkedChange = new EventEmitter<boolean>();

  isHovered = false;
  isFocused = false;
  switchOutput!: SwitchCoreOutput;
  CLASS_PREFIX = CLASS_PREFIX;

  ngOnChanges(): void {
    this.updateSwitchOutput();
    if (this.switchOutput.qualityWarnings.length > 0) {
      this.switchOutput.qualityWarnings.forEach((w) =>
        console.warn(`[Switch] ${w.message}`, w.details)
      );
    }
  }

  private updateSwitchOutput(): void {
    this.switchOutput = SwitchCore.processSwitch({
      tokens: {
        trackBackgroundColor: this.trackBackgroundColor,
        trackBorderColor: this.trackBorderColor,
        thumbColor: this.thumbColor,
        checkedTrackBackgroundColor: this.checkedTrackBackgroundColor,
      },
      isChecked: this.checked,
      disabled: this.disabled,
      isHovered: this.isHovered,
      isFocused: this.isFocused,
      hasError: this.error,
      size: this.size,
      label: this.label,
      helperText: this.helperText,
      errorMessage: this.errorMessage,
      required: this.required,
      userStyles: this.customStyle,
      customClass: this.customClass,
      showQualityWarnings: this.showQualityWarnings,
    });
  }

  getTrackStyle(): Record<string, string> {
    return {
      position: this.switchOutput.styles.trackPosition,
      display: this.switchOutput.styles.trackDisplay,
      width: `${this.switchOutput.styles.trackWidth}px`,
      height: `${this.switchOutput.styles.trackHeight}px`,
      backgroundColor: this.switchOutput.styles.trackBackgroundColor,
      borderWidth: `${this.switchOutput.styles.trackBorderWidth}px`,
      borderStyle: this.switchOutput.styles.trackBorderStyle,
      borderColor: this.switchOutput.styles.trackBorderColor,
      borderRadius: `${this.switchOutput.styles.trackBorderRadius}px`,
      cursor: this.switchOutput.styles.trackCursor,
      transition: this.switchOutput.styles.trackTransition,
      opacity: this.switchOutput.styles.trackOpacity.toString(),
      outline: this.switchOutput.styles.outlineColor
        ? `${this.switchOutput.styles.outlineWidth}px solid ${this.switchOutput.styles.outlineColor}`
        : 'none',
      outlineOffset: `${this.switchOutput.styles.outlineOffset}px`,
    };
  }

  getThumbStyle(): Record<string, string> {
    return {
      position: this.switchOutput.styles.thumbPosition,
      display: this.switchOutput.styles.thumbDisplay,
      top: '50%',
      left: `${this.switchOutput.styles.trackBorderWidth + 2}px`,
      width: `${this.switchOutput.styles.thumbWidth}px`,
      height: `${this.switchOutput.styles.thumbHeight}px`,
      backgroundColor: this.switchOutput.styles.thumbBackgroundColor,
      borderRadius: `${this.switchOutput.styles.thumbBorderRadius}px`,
      transition: this.switchOutput.styles.thumbTransition,
      transform: `translateY(-50%) ${this.switchOutput.styles.thumbTransform}`,
    };
  }

  onClick(): void {
    if (!this.disabled) {
      this.checkedChange.emit(!this.checked);
    }
  }

  onMouseEnter(): void {
    if (!this.disabled) {
      this.isHovered = true;
      this.updateSwitchOutput();
    }
  }

  onMouseLeave(): void {
    this.isHovered = false;
    this.updateSwitchOutput();
  }

  onFocus(): void {
    if (!this.disabled) {
      this.isFocused = true;
      this.updateSwitchOutput();
    }
  }

  onBlur(): void {
    this.isFocused = false;
    this.updateSwitchOutput();
  }

  get displayHelperText(): string | undefined {
    return this.error && this.errorMessage ? this.errorMessage : this.helperText;
  }
}

<div [class]="switchOutput.classNames" [ngStyle]="{ display: switchOutput.styles.containerDisplay, alignItems: switchOutput.styles.containerAlignItems, gap: switchOutput.styles.containerGap + 'px' }">
  <div
    [attr.role]="switchOutput.ariaAttrs.role"
    [attr.aria-checked]="switchOutput.ariaAttrs['aria-checked']"
    [attr.aria-disabled]="switchOutput.ariaAttrs['aria-disabled']"
    [attr.aria-required]="switchOutput.ariaAttrs['aria-required']"
    [attr.aria-invalid]="switchOutput.ariaAttrs['aria-invalid']"
    [attr.tabindex]="disabled ? -1 : 0"
    [class]="CLASS_PREFIX + '__track'"
    [ngStyle]="getTrackStyle()"
    (click)="onClick()"
    (mouseenter)="onMouseEnter()"
    (mouseleave)="onMouseLeave()"
    (focus)="onFocus()"
    (blur)="onBlur()"
  >
    <span [class]="CLASS_PREFIX + '__thumb'" [ngStyle]="getThumbStyle()"></span>
  </div>

  <label *ngIf="label" [class]="CLASS_PREFIX + '__label'" [ngStyle]="{ display: switchOutput.styles.labelDisplay, fontSize: switchOutput.styles.labelFontSize + 'px', color: switchOutput.styles.labelColor, fontWeight: switchOutput.styles.labelFontWeight }">
    {{ label }}<ng-container *ngIf="required"> *</ng-container>
  </label>

  <span *ngIf="displayHelperText" [class]="CLASS_PREFIX + '__helper'" [ngStyle]="{ display: switchOutput.styles.helperDisplay, fontSize: switchOutput.styles.helperFontSize + 'px', color: switchOutput.styles.helperColor }">
    {{ displayHelperText }}
  </span>
</div>
