// src/adapters/svelte/checkbox/Checkbox.svelte
<script lang="ts">
/**
 * @fileoverview Svelte Checkbox Adapter
 *
 * FASE 15: Component Expansion
 *
 * Svelte adapter for CheckboxCore.
 * This is a THIN wrapper that delegates all logic to CheckboxCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to CheckboxCore)
 * - ✅ 100% token-driven (via CheckboxCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/svelte/checkbox
 * @version 1.0.0
 */

import { onMount } from 'svelte';
import { CheckboxCore, CLASS_PREFIX } from '../../core/checkbox';
import type { CheckboxProps } from './types';

// ============================================================================
// PROPS
// ============================================================================

// Check state
export let checked: CheckboxProps['checked'] = false;
export let indeterminate: CheckboxProps['indeterminate'] = false;
export let label: CheckboxProps['label'] = undefined;

// Tokens - Base
export let backgroundColor: CheckboxProps['backgroundColor'];
export let borderColor: CheckboxProps['borderColor'];
export let checkColor: CheckboxProps['checkColor'];
export let labelColor: CheckboxProps['labelColor'] = undefined;

// Tokens - Hover
export let hoverBackgroundColor: CheckboxProps['hoverBackgroundColor'] = undefined;
export let hoverBorderColor: CheckboxProps['hoverBorderColor'] = undefined;

// Tokens - Focus
export let focusBackgroundColor: CheckboxProps['focusBackgroundColor'] = undefined;
export let focusBorderColor: CheckboxProps['focusBorderColor'] = undefined;
export let focusOutlineColor: CheckboxProps['focusOutlineColor'] = undefined;

// Tokens - Checked
export let checkedBackgroundColor: CheckboxProps['checkedBackgroundColor'] = undefined;
export let checkedBorderColor: CheckboxProps['checkedBorderColor'] = undefined;
export let checkedCheckColor: CheckboxProps['checkedCheckColor'] = undefined;

export let checkedHoverBackgroundColor: CheckboxProps['checkedHoverBackgroundColor'] = undefined;
export let checkedHoverBorderColor: CheckboxProps['checkedHoverBorderColor'] = undefined;
export let checkedHoverCheckColor: CheckboxProps['checkedHoverCheckColor'] = undefined;

export let checkedFocusBackgroundColor: CheckboxProps['checkedFocusBackgroundColor'] = undefined;
export let checkedFocusBorderColor: CheckboxProps['checkedFocusBorderColor'] = undefined;
export let checkedFocusCheckColor: CheckboxProps['checkedFocusCheckColor'] = undefined;
export let checkedFocusOutlineColor: CheckboxProps['checkedFocusOutlineColor'] = undefined;

// Tokens - Indeterminate
export let indeterminateBackgroundColor: CheckboxProps['indeterminateBackgroundColor'] = undefined;
export let indeterminateBorderColor: CheckboxProps['indeterminateBorderColor'] = undefined;
export let indeterminateCheckColor: CheckboxProps['indeterminateCheckColor'] = undefined;

export let indeterminateHoverBackgroundColor: CheckboxProps['indeterminateHoverBackgroundColor'] = undefined;
export let indeterminateHoverBorderColor: CheckboxProps['indeterminateHoverBorderColor'] = undefined;
export let indeterminateHoverCheckColor: CheckboxProps['indeterminateHoverCheckColor'] = undefined;

export let indeterminateFocusBackgroundColor: CheckboxProps['indeterminateFocusBackgroundColor'] = undefined;
export let indeterminateFocusBorderColor: CheckboxProps['indeterminateFocusBorderColor'] = undefined;
export let indeterminateFocusCheckColor: CheckboxProps['indeterminateFocusCheckColor'] = undefined;
export let indeterminateFocusOutlineColor: CheckboxProps['indeterminateFocusOutlineColor'] = undefined;

// Tokens - Disabled
export let disabledBackgroundColor: CheckboxProps['disabledBackgroundColor'] = undefined;
export let disabledBorderColor: CheckboxProps['disabledBorderColor'] = undefined;
export let disabledCheckColor: CheckboxProps['disabledCheckColor'] = undefined;
export let disabledLabelColor: CheckboxProps['disabledLabelColor'] = undefined;

export let checkedDisabledBackgroundColor: CheckboxProps['checkedDisabledBackgroundColor'] = undefined;
export let checkedDisabledBorderColor: CheckboxProps['checkedDisabledBorderColor'] = undefined;
export let checkedDisabledCheckColor: CheckboxProps['checkedDisabledCheckColor'] = undefined;

export let indeterminateDisabledBackgroundColor: CheckboxProps['indeterminateDisabledBackgroundColor'] = undefined;
export let indeterminateDisabledBorderColor: CheckboxProps['indeterminateDisabledBorderColor'] = undefined;
export let indeterminateDisabledCheckColor: CheckboxProps['indeterminateDisabledCheckColor'] = undefined;

// Behavior
export let disabled: CheckboxProps['disabled'] = false;
export let required: CheckboxProps['required'] = false;
export let invalid: CheckboxProps['invalid'] = false;

// Layout
export let size: CheckboxProps['size'] = 'md';

// Styling
let className: CheckboxProps['class'] = undefined;
export { className as class };
export let style: CheckboxProps['style'] = undefined;

// Accessibility
export let ariaLabel: CheckboxProps['ariaLabel'] = undefined;
export let ariaDescribedby: CheckboxProps['ariaDescribedby'] = undefined;
export let testId: CheckboxProps['testId'] = undefined;

// Developer experience
export let showQualityWarnings: CheckboxProps['showQualityWarnings'] = true;

// ============================================================================
// STATE (Svelte-specific)
// ============================================================================

let isHovered = false;
let isFocused = false;
let inputRef: HTMLInputElement | null = null;

// ============================================================================
// INDETERMINATE STATE SYNC
// ============================================================================

// Sync indeterminate state with native checkbox property
$: if (inputRef) {
  inputRef.indeterminate = indeterminate;
}

onMount(() => {
  if (inputRef) {
    inputRef.indeterminate = indeterminate;
  }
});

// ============================================================================
// CHECKBOX CORE INTEGRATION
// ============================================================================

/**
 * Process checkbox logic via CheckboxCore.
 *
 * This reactive statement delegates ALL logic to CheckboxCore.processCheckbox().
 * NO logic duplication - pure delegation.
 */
$: checkboxOutput = CheckboxCore.processCheckbox({
  // Tokens
  tokens: {
    backgroundColor,
    borderColor,
    checkColor,
    labelColor,
    hoverBackgroundColor,
    hoverBorderColor,
    focusBackgroundColor,
    focusBorderColor,
    focusOutlineColor,
    checkedBackgroundColor,
    checkedBorderColor,
    checkedCheckColor,
    checkedHoverBackgroundColor,
    checkedHoverBorderColor,
    checkedHoverCheckColor,
    checkedFocusBackgroundColor,
    checkedFocusBorderColor,
    checkedFocusCheckColor,
    checkedFocusOutlineColor,
    indeterminateBackgroundColor,
    indeterminateBorderColor,
    indeterminateCheckColor,
    indeterminateHoverBackgroundColor,
    indeterminateHoverBorderColor,
    indeterminateHoverCheckColor,
    indeterminateFocusBackgroundColor,
    indeterminateFocusBorderColor,
    indeterminateFocusCheckColor,
    indeterminateFocusOutlineColor,
    disabledBackgroundColor,
    disabledBorderColor,
    disabledCheckColor,
    disabledLabelColor,
    checkedDisabledBackgroundColor,
    checkedDisabledBorderColor,
    checkedDisabledCheckColor,
    indeterminateDisabledBackgroundColor,
    indeterminateDisabledBorderColor,
    indeterminateDisabledCheckColor,
  },

  // Check state
  isChecked: checked,
  isIndeterminate: indeterminate,

  // Interaction state
  disabled,
  isHovered,
  isFocused,

  // Layout
  size,

  // Content
  label,

  // ARIA
  required,
  invalid,
  ariaLabel,
  ariaDescribedby,

  // Styles
  userStyles: style,

  // Dev mode
  showQualityWarnings,
  customClass: className,
});

// ============================================================================
// QUALITY WARNINGS (DEV MODE)
// ============================================================================

// Log quality warnings
$: if (checkboxOutput.qualityWarnings.length > 0) {
  checkboxOutput.qualityWarnings.forEach((warning) => {
    console.warn(`[Checkbox] ${warning.message}`, warning.details);
  });
}

// ============================================================================
// COMPUTED STYLES
// ============================================================================

$: containerStyles = [
  `display: ${checkboxOutput.styles.containerDisplay}`,
  `align-items: ${checkboxOutput.styles.containerAlignItems}`,
  `gap: ${checkboxOutput.styles.containerGap}px`,
  `cursor: ${checkboxOutput.styles.containerCursor}`,
  `opacity: ${checkboxOutput.styles.containerOpacity}`,
].join('; ');

$: boxStyles = [
  'position: relative',
  `width: ${checkboxOutput.styles.boxWidth}px`,
  `height: ${checkboxOutput.styles.boxHeight}px`,
  `background-color: ${checkboxOutput.styles.boxBackgroundColor}`,
  `border-width: ${checkboxOutput.styles.boxBorderWidth}px`,
  `border-style: ${checkboxOutput.styles.boxBorderStyle}`,
  `border-color: ${checkboxOutput.styles.boxBorderColor}`,
  `border-radius: ${checkboxOutput.styles.boxBorderRadius}px`,
  `display: ${checkboxOutput.styles.boxDisplay}`,
  `align-items: ${checkboxOutput.styles.boxAlignItems}`,
  `justify-content: ${checkboxOutput.styles.boxJustifyContent}`,
  `transition: ${checkboxOutput.styles.boxTransition}`,
  checkboxOutput.styles.outlineColor ? `outline: ${checkboxOutput.styles.outlineWidth}px solid ${checkboxOutput.styles.outlineColor}` : '',
  checkboxOutput.styles.outlineColor ? `outline-offset: ${checkboxOutput.styles.outlineOffset}px` : '',
].filter(Boolean).join('; ');

$: iconStyles = [
  `width: ${checkboxOutput.styles.iconSize}px`,
  `height: ${checkboxOutput.styles.iconSize}px`,
  `color: ${checkboxOutput.styles.iconColor}`,
  `display: ${checkboxOutput.styles.iconDisplay}`,
].join('; ');

$: labelStyles = checkboxOutput.styles.labelColor ? [
  `font-size: ${checkboxOutput.styles.labelFontSize}px`,
  `color: ${checkboxOutput.styles.labelColor}`,
].join('; ') : '';

$: showIcon = checked || indeterminate;

// ============================================================================
// EVENT HANDLERS (Svelte-specific)
// ============================================================================

import { createEventDispatcher } from 'svelte';

const dispatch = createEventDispatcher<{
  change: boolean;
  focus: FocusEvent;
  blur: FocusEvent;
}>();

function handleChange(event: Event) {
  if (disabled) {
    return;
  }
  const target = event.target as HTMLInputElement;
  checked = target.checked;
  dispatch('change', checked);
}

function handleMouseEnter() {
  if (disabled) {
    return;
  }
  isHovered = true;
}

function handleMouseLeave() {
  isHovered = false;
}

function handleFocus(event: FocusEvent) {
  if (disabled) {
    return;
  }
  isFocused = true;
  dispatch('focus', event);
}

function handleBlur(event: FocusEvent) {
  isFocused = false;
  dispatch('blur', event);
}
</script>

<label
  style={containerStyles}
  class={checkboxOutput.classNames}
  on:mouseenter={handleMouseEnter}
  on:mouseleave={handleMouseLeave}
>
  <!-- Hidden native checkbox (for accessibility and form submission) -->
  <input
    bind:this={inputRef}
    type="checkbox"
    {checked}
    on:change={handleChange}
    on:focus={handleFocus}
    on:blur={handleBlur}
    {disabled}
    {required}
    style="position: absolute; opacity: 0; width: 1px; height: 1px; margin: -1px;"
    aria-checked={checkboxOutput.ariaAttrs['aria-checked']}
    aria-disabled={checkboxOutput.ariaAttrs['aria-disabled']}
    aria-label={checkboxOutput.ariaAttrs['aria-label']}
    aria-describedby={checkboxOutput.ariaAttrs['aria-describedby']}
    aria-required={checkboxOutput.ariaAttrs['aria-required']}
    aria-invalid={checkboxOutput.ariaAttrs['aria-invalid']}
    data-momoto-bg-quality={showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.qualityScore : undefined}
    data-momoto-bg-decision={showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined}
    data-momoto-check-quality={showQualityWarnings ? checkboxOutput.resolvedTokens.checkColor.qualityScore : undefined}
    data-testid={testId}
  />

  <!-- Visual checkbox box -->
  <span
    class="{CLASS_PREFIX}__box"
    style={boxStyles}
  >
    <!-- Checkmark or dash icon -->
    {#if showIcon}
      <svg
        class="{CLASS_PREFIX}__icon"
        style={iconStyles}
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
      >
        {#if indeterminate}
          <!-- Dash icon for indeterminate state -->
          <path
            d="M4 8h8"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
          />
        {:else}
          <!-- Checkmark icon for checked state -->
          <path
            d="M3 8l3 3 7-7"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        {/if}
      </svg>
    {/if}
  </span>

  <!-- Label (optional) -->
  {#if label}
    <span
      class="{CLASS_PREFIX}__label"
      style={labelStyles}
    >
      {label}
    </span>
  {/if}
</label>

<!--
CONTRACT COMPLIANCE:

✅ Zero logic duplication
   - ALL logic delegated to CheckboxCore.processCheckbox()
   - Adapter is THIN wrapper

✅ 100% token-driven
   - All colors from EnrichedToken (via CheckboxCore)
   - NO local color calculations

✅ State management via framework
   - Uses Svelte's reactive let for interaction state
   - CheckboxCore handles state determination

✅ Framework-specific concerns only
   - Template rendering (Svelte-specific)
   - Event handling (Svelte events → CheckboxCore)
   - Reactivity (Svelte $: reactive statements)
   - Indeterminate state sync (Svelte $: + onMount)

✅ Identical behavior to React/Vue
   - Same CheckboxCore
   - Same tokens
   - Same output

✅ Tri-state support
   - Unchecked, checked, indeterminate
   - Proper ARIA compliance

PATTERN: Exact copy of TextField.svelte adapted for Checkbox
-->

// src/adapters/vue/checkbox/Checkbox.vue
<template>
  <label
    :style="containerStyles"
    :class="checkboxOutput.classNames"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <!-- Hidden native checkbox (for accessibility and form submission) -->
    <input
      ref="inputRef"
      type="checkbox"
      :checked="checked"
      @change="handleChange"
      @focus="handleFocus"
      @blur="handleBlur"
      :disabled="disabled"
      :required="required"
      :style="{
        position: 'absolute',
        opacity: 0,
        width: '1px',
        height: '1px',
        margin: '-1px',
      }"
      :aria-checked="checkboxOutput.ariaAttrs['aria-checked']"
      :aria-disabled="checkboxOutput.ariaAttrs['aria-disabled']"
      :aria-label="checkboxOutput.ariaAttrs['aria-label']"
      :aria-describedby="checkboxOutput.ariaAttrs['aria-describedby']"
      :aria-required="checkboxOutput.ariaAttrs['aria-required']"
      :aria-invalid="checkboxOutput.ariaAttrs['aria-invalid']"
      :data-momoto-bg-quality="showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.qualityScore : undefined"
      :data-momoto-bg-decision="showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined"
      :data-momoto-check-quality="showQualityWarnings ? checkboxOutput.resolvedTokens.checkColor.qualityScore : undefined"
      :data-testid="testId"
    />

    <!-- Visual checkbox box -->
    <span
      :class="`${CLASS_PREFIX}__box`"
      :style="boxStyles"
    >
      <!-- Checkmark or dash icon -->
      <svg
        v-if="showIcon"
        :class="`${CLASS_PREFIX}__icon`"
        :style="iconStyles"
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
      >
        <path
          v-if="indeterminate"
          d="M4 8h8"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <path
          v-else
          d="M3 8l3 3 7-7"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </span>

    <!-- Label (optional) -->
    <span
      v-if="label"
      :class="`${CLASS_PREFIX}__label`"
      :style="labelStyles"
    >
      {{ label }}
    </span>
  </label>
</template>

<script setup lang="ts">
/**
 * @fileoverview Vue Checkbox Adapter
 *
 * FASE 15: Component Expansion
 *
 * Vue 3 adapter for CheckboxCore.
 * This is a THIN wrapper that delegates all logic to CheckboxCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to CheckboxCore)
 * - ✅ 100% token-driven (via CheckboxCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/vue/checkbox
 * @version 1.0.0
 */

import { ref, computed, watch, onMounted } from 'vue';
import { CheckboxCore, CLASS_PREFIX } from '../../core/checkbox';
import type { CheckboxProps } from './types';

// ============================================================================
// PROPS
// ============================================================================

const props = withDefaults(defineProps<CheckboxProps>(), {
  // Check state
  checked: false,
  indeterminate: false,

  // Behavior
  disabled: false,
  required: false,
  invalid: false,

  // Layout
  size: 'md',

  // Dev mode
  showQualityWarnings: import.meta.env.DEV,
});

// ============================================================================
// EMITS
// ============================================================================

const emit = defineEmits<{
  'update:checked': [checked: boolean];
  focus: [event: FocusEvent];
  blur: [event: FocusEvent];
}>();

// ============================================================================
// STATE (Vue-specific)
// ============================================================================

const isHovered = ref(false);
const isFocused = ref(false);
const inputRef = ref<HTMLInputElement | null>(null);

// ============================================================================
// INDETERMINATE STATE SYNC
// ============================================================================

// Sync indeterminate state with native checkbox property
watch(() => props.indeterminate, (newVal) => {
  if (inputRef.value) {
    inputRef.value.indeterminate = newVal;
  }
});

onMounted(() => {
  if (inputRef.value) {
    inputRef.value.indeterminate = props.indeterminate;
  }
});

// ============================================================================
// CHECKBOX CORE INTEGRATION
// ============================================================================

/**
 * Process checkbox logic via CheckboxCore.
 *
 * This computed property delegates ALL logic to CheckboxCore.processCheckbox().
 * NO logic duplication - pure delegation.
 */
const checkboxOutput = computed(() => {
  return CheckboxCore.processCheckbox({
    // Tokens
    tokens: {
      backgroundColor: props.backgroundColor,
      borderColor: props.borderColor,
      checkColor: props.checkColor,
      labelColor: props.labelColor,
      hoverBackgroundColor: props.hoverBackgroundColor,
      hoverBorderColor: props.hoverBorderColor,
      focusBackgroundColor: props.focusBackgroundColor,
      focusBorderColor: props.focusBorderColor,
      focusOutlineColor: props.focusOutlineColor,
      checkedBackgroundColor: props.checkedBackgroundColor,
      checkedBorderColor: props.checkedBorderColor,
      checkedCheckColor: props.checkedCheckColor,
      checkedHoverBackgroundColor: props.checkedHoverBackgroundColor,
      checkedHoverBorderColor: props.checkedHoverBorderColor,
      checkedHoverCheckColor: props.checkedHoverCheckColor,
      checkedFocusBackgroundColor: props.checkedFocusBackgroundColor,
      checkedFocusBorderColor: props.checkedFocusBorderColor,
      checkedFocusCheckColor: props.checkedFocusCheckColor,
      checkedFocusOutlineColor: props.checkedFocusOutlineColor,
      indeterminateBackgroundColor: props.indeterminateBackgroundColor,
      indeterminateBorderColor: props.indeterminateBorderColor,
      indeterminateCheckColor: props.indeterminateCheckColor,
      indeterminateHoverBackgroundColor: props.indeterminateHoverBackgroundColor,
      indeterminateHoverBorderColor: props.indeterminateHoverBorderColor,
      indeterminateHoverCheckColor: props.indeterminateHoverCheckColor,
      indeterminateFocusBackgroundColor: props.indeterminateFocusBackgroundColor,
      indeterminateFocusBorderColor: props.indeterminateFocusBorderColor,
      indeterminateFocusCheckColor: props.indeterminateFocusCheckColor,
      indeterminateFocusOutlineColor: props.indeterminateFocusOutlineColor,
      disabledBackgroundColor: props.disabledBackgroundColor,
      disabledBorderColor: props.disabledBorderColor,
      disabledCheckColor: props.disabledCheckColor,
      disabledLabelColor: props.disabledLabelColor,
      checkedDisabledBackgroundColor: props.checkedDisabledBackgroundColor,
      checkedDisabledBorderColor: props.checkedDisabledBorderColor,
      checkedDisabledCheckColor: props.checkedDisabledCheckColor,
      indeterminateDisabledBackgroundColor: props.indeterminateDisabledBackgroundColor,
      indeterminateDisabledBorderColor: props.indeterminateDisabledBorderColor,
      indeterminateDisabledCheckColor: props.indeterminateDisabledCheckColor,
    },

    // Check state
    isChecked: props.checked,
    isIndeterminate: props.indeterminate,

    // Interaction state
    disabled: props.disabled,
    isHovered: isHovered.value,
    isFocused: isFocused.value,

    // Layout
    size: props.size,

    // Content
    label: props.label,

    // ARIA
    required: props.required,
    invalid: props.invalid,
    ariaLabel: props.ariaLabel,
    ariaDescribedby: props.ariaDescribedby,

    // Styles
    userStyles: props.style,

    // Dev mode
    showQualityWarnings: props.showQualityWarnings,
    customClass: props.class,
  });
});

// ============================================================================
// QUALITY WARNINGS (DEV MODE)
// ============================================================================

// Watch for quality warnings and log them
watch(
  () => checkboxOutput.value.qualityWarnings,
  (warnings) => {
    if (warnings.length > 0) {
      warnings.forEach((warning) => {
        console.warn(`[Checkbox] ${warning.message}`, warning.details);
      });
    }
  },
  { immediate: true }
);

// ============================================================================
// COMPUTED STYLES
// ============================================================================

const containerStyles = computed(() => ({
  display: checkboxOutput.value.styles.containerDisplay,
  alignItems: checkboxOutput.value.styles.containerAlignItems,
  gap: `${checkboxOutput.value.styles.containerGap}px`,
  cursor: checkboxOutput.value.styles.containerCursor,
  opacity: checkboxOutput.value.styles.containerOpacity,
}));

const boxStyles = computed(() => {
  const styles: Record<string, string | number> = {
    position: 'relative',
    width: `${checkboxOutput.value.styles.boxWidth}px`,
    height: `${checkboxOutput.value.styles.boxHeight}px`,
    backgroundColor: checkboxOutput.value.styles.boxBackgroundColor,
    borderWidth: `${checkboxOutput.value.styles.boxBorderWidth}px`,
    borderStyle: checkboxOutput.value.styles.boxBorderStyle,
    borderColor: checkboxOutput.value.styles.boxBorderColor,
    borderRadius: `${checkboxOutput.value.styles.boxBorderRadius}px`,
    display: checkboxOutput.value.styles.boxDisplay || 'inline-flex',
    alignItems: checkboxOutput.value.styles.boxAlignItems || 'center',
    justifyContent: checkboxOutput.value.styles.boxJustifyContent || 'center',
    transition: checkboxOutput.value.styles.boxTransition || 'none',
  };

  if (checkboxOutput.value.styles.outlineColor) {
    styles.outline = `${checkboxOutput.value.styles.outlineWidth}px solid ${checkboxOutput.value.styles.outlineColor}`;
    styles.outlineOffset = `${checkboxOutput.value.styles.outlineOffset}px`;
  }

  return styles;
});

const iconStyles = computed(() => ({
  width: `${checkboxOutput.value.styles.iconSize}px`,
  height: `${checkboxOutput.value.styles.iconSize}px`,
  color: checkboxOutput.value.styles.iconColor,
  display: checkboxOutput.value.styles.iconDisplay,
}));

const labelStyles = computed(() => checkboxOutput.value.styles.labelColor ? {
  fontSize: `${checkboxOutput.value.styles.labelFontSize}px`,
  color: checkboxOutput.value.styles.labelColor,
} : undefined);

const showIcon = computed(() => props.checked || props.indeterminate);

// ============================================================================
// EVENT HANDLERS (Vue-specific)
// ============================================================================

function handleChange(event: Event) {
  if (props.disabled) {
    return;
  }
  const target = event.target as HTMLInputElement;
  emit('update:checked', target.checked);
}

function handleMouseEnter() {
  if (props.disabled) {
    return;
  }
  isHovered.value = true;
}

function handleMouseLeave() {
  isHovered.value = false;
}

function handleFocus(event: FocusEvent) {
  if (props.disabled) {
    return;
  }
  isFocused.value = true;
  emit('focus', event);
}

function handleBlur(event: FocusEvent) {
  isFocused.value = false;
  emit('blur', event);
}
</script>

<!--
CONTRACT COMPLIANCE:

✅ Zero logic duplication
   - ALL logic delegated to CheckboxCore.processCheckbox()
   - Adapter is THIN wrapper

✅ 100% token-driven
   - All colors from EnrichedToken (via CheckboxCore)
   - NO local color calculations

✅ State management via framework
   - Uses Vue's ref() for interaction state
   - CheckboxCore handles state determination

✅ Framework-specific concerns only
   - Template rendering (Vue-specific)
   - Event handling (Vue events → CheckboxCore)
   - Reactivity (Vue computed)
   - Indeterminate state sync (Vue watch + onMounted)

✅ Identical behavior to React
   - Same CheckboxCore
   - Same tokens
   - Same output

✅ Tri-state support
   - Unchecked, checked, indeterminate
   - Proper ARIA compliance

PATTERN: Exact copy of TextField.vue adapted for Checkbox
-->
