// src/adapters/angular/textfield/textfield.component.ts
/**
 * @fileoverview Angular TextField Adapter
 *
 * FASE 15: Component Expansion
 *
 * Angular adapter for TextFieldCore.
 * This is a THIN wrapper that delegates all logic to TextFieldCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to TextFieldCore)
 * - ✅ 100% token-driven (via TextFieldCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/angular/textfield
 * @version 1.0.0
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnChanges,
  SimpleChanges,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TextFieldCore, CLASS_PREFIX } from '../../core/textfield';
import type {
  TextFieldSize,
  TextFieldStyles,
  ResolvedTextFieldTokens,
  TextFieldState,
  SizeConfig,
  QualityWarning,
  ARIAAttributes,
} from '../../core/textfield/textFieldCore.types';
import type { EnrichedToken } from '../../../domain/tokens/value-objects/EnrichedToken';

@Component({
  selector: 'momoto-textfield',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './textfield.component.html',
  styleUrls: ['./textfield.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TextFieldComponent implements OnChanges {
  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - CONTENT
  // ══════════════════════════════════════════════════════════════════════════

  @Input({ required: true }) value!: string;
  @Input() placeholder?: string;
  @Input() label?: string;
  @Input() helperText?: string;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (BASE)
  // ══════════════════════════════════════════════════════════════════════════

  @Input({ required: true }) backgroundColor!: EnrichedToken;
  @Input({ required: true }) textColor!: EnrichedToken;
  @Input() borderColor?: EnrichedToken | null;
  @Input() placeholderColor?: EnrichedToken | null;
  @Input() labelColor?: EnrichedToken | null;
  @Input() helperTextColor?: EnrichedToken | null;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (HOVER)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() hoverBackgroundColor?: EnrichedToken;
  @Input() hoverBorderColor?: EnrichedToken | null;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (FOCUS)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() focusBackgroundColor?: EnrichedToken;
  @Input() focusBorderColor?: EnrichedToken | null;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (ERROR)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() errorBackgroundColor?: EnrichedToken;
  @Input() errorTextColor?: EnrichedToken;
  @Input() errorBorderColor?: EnrichedToken | null;
  @Input() errorLabelColor?: EnrichedToken | null;
  @Input() errorHelperTextColor?: EnrichedToken | null;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (SUCCESS)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() successBackgroundColor?: EnrichedToken;
  @Input() successTextColor?: EnrichedToken;
  @Input() successBorderColor?: EnrichedToken | null;
  @Input() successLabelColor?: EnrichedToken | null;
  @Input() successHelperTextColor?: EnrichedToken | null;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (DISABLED)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() disabledBackgroundColor?: EnrichedToken;
  @Input() disabledTextColor?: EnrichedToken;
  @Input() disabledBorderColor?: EnrichedToken | null;
  @Input() disabledLabelColor?: EnrichedToken | null;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - BEHAVIOR
  // ══════════════════════════════════════════════════════════════════════════

  @Input() type: 'text' | 'email' | 'password' | 'tel' | 'url' | 'search' | 'number' = 'text';
  @Input() disabled = false;
  @Input() error = false;
  @Input() success = false;
  @Input() required = false;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - LAYOUT
  // ══════════════════════════════════════════════════════════════════════════

  @Input() size: TextFieldSize = 'md';
  @Input() fullWidth = false;
  @Input() multiline = false;
  @Input() rows = 3;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - STYLING
  // ══════════════════════════════════════════════════════════════════════════

  @Input() customClass?: string;
  @Input() customStyle?: Partial<TextFieldStyles>;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - ACCESSIBILITY
  // ══════════════════════════════════════════════════════════════════════════

  @Input() ariaLabel?: string;
  @Input() ariaDescribedby?: string;
  @Input() testId?: string;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - DEVELOPER EXPERIENCE
  // ══════════════════════════════════════════════════════════════════════════

  @Input() showQualityWarnings = true;

  // ══════════════════════════════════════════════════════════════════════════
  // OUTPUTS
  // ══════════════════════════════════════════════════════════════════════════

  @Output() valueChange = new EventEmitter<string>();
  @Output() textFieldFocus = new EventEmitter<FocusEvent>();
  @Output() textFieldBlur = new EventEmitter<FocusEvent>();

  // ══════════════════════════════════════════════════════════════════════════
  // STATE (Angular-specific)
  // ══════════════════════════════════════════════════════════════════════════

  protected isHovered = false;
  protected isFocused = false;

  // ══════════════════════════════════════════════════════════════════════════
  // TEXTFIELD CORE OUTPUT (computed)
  // ══════════════════════════════════════════════════════════════════════════

  protected currentState!: TextFieldState;
  protected resolvedTokens!: ResolvedTextFieldTokens;
  protected textFieldStyles!: TextFieldStyles;
  protected ariaAttrs!: ARIAAttributes;
  protected classNames!: string;
  protected sizeConfig!: SizeConfig;
  protected qualityWarnings: QualityWarning[] = [];

  // Class prefix for template
  protected readonly CLASS_PREFIX = CLASS_PREFIX;

  // ══════════════════════════════════════════════════════════════════════════
  // LIFECYCLE
  // ══════════════════════════════════════════════════════════════════════════

  ngOnChanges(changes: SimpleChanges): void {
    // Recompute text field output when inputs change
    this.updateTextFieldOutput();
  }

  // ══════════════════════════════════════════════════════════════════════════
  // TEXTFIELD CORE INTEGRATION
  // ══════════════════════════════════════════════════════════════════════════

  /**
   * Update text field output via TextFieldCore.
   *
   * This method delegates ALL logic to TextFieldCore.processTextField().
   * NO logic duplication - pure delegation.
   */
  private updateTextFieldOutput(): void {
    const output = TextFieldCore.processTextField({
      // Tokens
      tokens: {
        backgroundColor: this.backgroundColor,
        textColor: this.textColor,
        borderColor: this.borderColor,
        placeholderColor: this.placeholderColor,
        labelColor: this.labelColor,
        helperTextColor: this.helperTextColor,
        hoverBackgroundColor: this.hoverBackgroundColor,
        hoverBorderColor: this.hoverBorderColor,
        focusBackgroundColor: this.focusBackgroundColor,
        focusBorderColor: this.focusBorderColor,
        errorBackgroundColor: this.errorBackgroundColor,
        errorTextColor: this.errorTextColor,
        errorBorderColor: this.errorBorderColor,
        errorLabelColor: this.errorLabelColor,
        errorHelperTextColor: this.errorHelperTextColor,
        successBackgroundColor: this.successBackgroundColor,
        successTextColor: this.successTextColor,
        successBorderColor: this.successBorderColor,
        successLabelColor: this.successLabelColor,
        successHelperTextColor: this.successHelperTextColor,
        disabledBackgroundColor: this.disabledBackgroundColor,
        disabledTextColor: this.disabledTextColor,
        disabledBorderColor: this.disabledBorderColor,
        disabledLabelColor: this.disabledLabelColor,
      },

      // Interaction state
      disabled: this.disabled,
      error: this.error,
      success: this.success,
      isHovered: this.isHovered,
      isFocused: this.isFocused,

      // Layout
      size: this.size,
      fullWidth: this.fullWidth,
      multiline: this.multiline,

      // Content
      label: this.label,
      helperText: this.helperText,

      // ARIA
      required: this.required,
      ariaLabel: this.ariaLabel,
      ariaDescribedby: this.ariaDescribedby,

      // Styles
      userStyles: this.customStyle,

      // Dev mode
      showQualityWarnings: this.showQualityWarnings,
      customClass: this.customClass,
    });

    // Update component properties
    this.currentState = output.currentState;
    this.resolvedTokens = output.resolvedTokens;
    this.textFieldStyles = output.styles;
    this.ariaAttrs = output.ariaAttrs;
    this.classNames = output.classNames;
    this.sizeConfig = output.sizeConfig;
    this.qualityWarnings = output.qualityWarnings;

    // Log quality warnings
    if (this.qualityWarnings.length > 0) {
      this.qualityWarnings.forEach((warning) => {
        console.warn(`[TextField] ${warning.message}`, warning.details);
      });
    }
  }

  // ══════════════════════════════════════════════════════════════════════════
  // EVENT HANDLERS (Angular-specific)
  // ══════════════════════════════════════════════════════════════════════════

  protected onInput(event: Event): void {
    if (this.disabled) {
      return;
    }
    const target = event.target as HTMLInputElement | HTMLTextAreaElement;
    this.value = target.value;
    this.valueChange.emit(this.value);
  }

  protected onMouseEnter(): void {
    if (this.disabled) {
      return;
    }
    this.isHovered = true;
    this.updateTextFieldOutput();
  }

  protected onMouseLeave(): void {
    this.isHovered = false;
    this.updateTextFieldOutput();
  }

  protected onFocus(event: FocusEvent): void {
    if (this.disabled) {
      return;
    }
    this.isFocused = true;
    this.updateTextFieldOutput();
    this.textFieldFocus.emit(event);
  }

  protected onBlur(event: FocusEvent): void {
    this.isFocused = false;
    this.updateTextFieldOutput();
    this.textFieldBlur.emit(event);
  }

  // ══════════════════════════════════════════════════════════════════════════
  // TEMPLATE UTILITIES
  // ══════════════════════════════════════════════════════════════════════════

  /**
   * Get container style object for [ngStyle].
   */
  protected getContainerStyle(): Record<string, string | number> {
    return {
      'width': this.textFieldStyles.containerWidth || 'auto',
      'display': this.textFieldStyles.containerDisplay || 'flex',
      'flex-direction': this.textFieldStyles.containerFlexDirection || 'column',
      'gap': `${this.textFieldStyles.containerGap}px`,
    };
  }

  /**
   * Get input style object for [ngStyle].
   */
  protected getInputStyle(): Record<string, string | number> {
    const styles: Record<string, string | number> = {
      'height': this.multiline ? 'auto' : `${this.textFieldStyles.inputHeight}px`,
      'padding-left': `${this.textFieldStyles.inputPaddingLeft}px`,
      'padding-right': `${this.textFieldStyles.inputPaddingRight}px`,
      'padding-top': `${this.textFieldStyles.inputPaddingTop}px`,
      'padding-bottom': `${this.textFieldStyles.inputPaddingBottom}px`,
      'font-size': `${this.textFieldStyles.inputFontSize}px`,
      'font-weight': this.textFieldStyles.inputFontWeight || 400,
      'line-height': this.textFieldStyles.inputLineHeight || 1.5,
      'font-family': this.textFieldStyles.inputFontFamily || 'inherit',
      'background-color': this.textFieldStyles.inputBackgroundColor || 'transparent',
      'color': this.textFieldStyles.inputColor || 'inherit',
      'border-radius': `${this.textFieldStyles.inputBorderRadius}px`,
      'outline': this.textFieldStyles.inputOutline || 'none',
      'cursor': this.textFieldStyles.inputCursor || 'text',
      'transition': this.textFieldStyles.inputTransition || 'none',
    };

    if (this.textFieldStyles.inputBorderWidth) {
      styles['border-width'] = `${this.textFieldStyles.inputBorderWidth}px`;
    }
    if (this.textFieldStyles.inputBorderStyle) {
      styles['border-style'] = this.textFieldStyles.inputBorderStyle;
    }
    if (this.textFieldStyles.inputBorderColor) {
      styles['border-color'] = this.textFieldStyles.inputBorderColor;
    }

    return styles;
  }

  /**
   * Get label style object for [ngStyle].
   */
  protected getLabelStyle(): Record<string, string | number> | null {
    if (!this.textFieldStyles.labelColor) {
      return null;
    }

    return {
      'font-size': `${this.textFieldStyles.labelFontSize}px`,
      'font-weight': this.textFieldStyles.labelFontWeight || 500,
      'color': this.textFieldStyles.labelColor,
      'margin-bottom': `${this.textFieldStyles.labelMarginBottom}px`,
    };
  }

  /**
   * Get helper text style object for [ngStyle].
   */
  protected getHelperStyle(): Record<string, string | number> | null {
    if (!this.textFieldStyles.helperColor) {
      return null;
    }

    return {
      'font-size': `${this.textFieldStyles.helperFontSize}px`,
      'color': this.textFieldStyles.helperColor,
      'margin-top': `${this.textFieldStyles.helperMarginTop}px`,
    };
  }
}

/**
 * CONTRACT COMPLIANCE:
 *
 * ✅ Zero logic duplication
 *    - ALL logic delegated to TextFieldCore.processTextField()
 *    - Component is wrapper around TextFieldCore
 *    - Adapter is THIN
 *
 * ✅ 100% token-driven
 *    - All colors from EnrichedToken (via TextFieldCore)
 *    - NO local color calculations
 *
 * ✅ State management via framework
 *    - Uses Angular component properties for interaction state
 *    - TextFieldCore handles state determination
 *
 * ✅ Framework-specific concerns only
 *    - Template rendering (Angular-specific)
 *    - Event handling (Angular events → TextFieldCore)
 *    - Change detection (Angular OnChanges)
 *
 * ✅ Identical behavior to React/Vue/Svelte
 *    - Same TextFieldCore
 *    - Same tokens
 *    - Same output
 *
 * PATTERN: Exact copy of button.component.ts adapted for TextField
 */

<div
  [class]="classNames"
  [ngStyle]="getContainerStyle()"
>
  <!-- Label (optional) -->
  <label
    *ngIf="label"
    [class]="CLASS_PREFIX + '__label'"
    [ngStyle]="getLabelStyle()"
  >
    {{ label }}
    <span *ngIf="required" aria-label="required"> *</span>
  </label>

  <!-- Input (single-line) -->
  <input
    *ngIf="!multiline"
    [type]="type"
    [(ngModel)]="value"
    [placeholder]="placeholder || ''"
    [disabled]="disabled"
    [required]="required"
    [class]="CLASS_PREFIX + '__input'"
    [ngStyle]="getInputStyle()"
    [attr.aria-label]="ariaAttrs['aria-label']"
    [attr.aria-describedby]="ariaAttrs['aria-describedby']"
    [attr.aria-disabled]="ariaAttrs['aria-disabled']"
    [attr.aria-invalid]="ariaAttrs['aria-invalid']"
    [attr.aria-required]="ariaAttrs['aria-required']"
    [attr.data-momoto-bg-quality]="showQualityWarnings ? resolvedTokens.backgroundColor.qualityScore : undefined"
    [attr.data-momoto-bg-decision]="showQualityWarnings ? resolvedTokens.backgroundColor.sourceDecisionId : undefined"
    [attr.data-momoto-text-quality]="showQualityWarnings ? resolvedTokens.textColor.qualityScore : undefined"
    [attr.data-momoto-wcag-ratio]="showQualityWarnings ? resolvedTokens.textColor.accessibility?.wcagRatio : undefined"
    [attr.data-testid]="testId"
    (input)="onInput($event)"
    (focus)="onFocus($event)"
    (blur)="onBlur($event)"
    (mouseenter)="onMouseEnter()"
    (mouseleave)="onMouseLeave()"
  />

  <!-- Textarea (multiline) -->
  <textarea
    *ngIf="multiline"
    [(ngModel)]="value"
    [placeholder]="placeholder || ''"
    [disabled]="disabled"
    [required]="required"
    [rows]="rows"
    [class]="CLASS_PREFIX + '__input ' + CLASS_PREFIX + '__input--multiline'"
    [ngStyle]="getInputStyle()"
    [attr.aria-label]="ariaAttrs['aria-label']"
    [attr.aria-describedby]="ariaAttrs['aria-describedby']"
    [attr.aria-disabled]="ariaAttrs['aria-disabled']"
    [attr.aria-invalid]="ariaAttrs['aria-invalid']"
    [attr.aria-required]="ariaAttrs['aria-required']"
    [attr.data-momoto-bg-quality]="showQualityWarnings ? resolvedTokens.backgroundColor.qualityScore : undefined"
    [attr.data-momoto-bg-decision]="showQualityWarnings ? resolvedTokens.backgroundColor.sourceDecisionId : undefined"
    [attr.data-momoto-text-quality]="showQualityWarnings ? resolvedTokens.textColor.qualityScore : undefined"
    [attr.data-momoto-wcag-ratio]="showQualityWarnings ? resolvedTokens.textColor.accessibility?.wcagRatio : undefined"
    [attr.data-testid]="testId"
    (input)="onInput($event)"
    (focus)="onFocus($event)"
    (blur)="onBlur($event)"
    (mouseenter)="onMouseEnter()"
    (mouseleave)="onMouseLeave()"
  ></textarea>

  <!-- Helper text (optional) -->
  <div
    *ngIf="helperText"
    [class]="CLASS_PREFIX + '__helper'"
    [ngStyle]="getHelperStyle()"
  >
    {{ helperText }}
  </div>
</div>

// adapters/svelte/textfield/TextField.svelte
<script lang="ts">
/**
 * @fileoverview Svelte TextField Adapter
 *
 * FASE 15: Component Expansion
 *
 * Svelte adapter for TextFieldCore.
 * This is a THIN wrapper that delegates all logic to TextFieldCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to TextFieldCore)
 * - ✅ 100% token-driven (via TextFieldCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/svelte/textfield
 * @version 1.0.0
 */

import { createEventDispatcher } from 'svelte';
import { TextFieldCore, CLASS_PREFIX } from '../../core/textfield';
import type { TextFieldProps } from './types';

// ============================================================================
// PROPS
// ============================================================================

// Content
export let value: TextFieldProps['value'];
export let placeholder: TextFieldProps['placeholder'] = undefined;
export let label: TextFieldProps['label'] = undefined;
export let helperText: TextFieldProps['helperText'] = undefined;

// Tokens - Base
export let backgroundColor: TextFieldProps['backgroundColor'];
export let textColor: TextFieldProps['textColor'];
export let borderColor: TextFieldProps['borderColor'] = undefined;
export let placeholderColor: TextFieldProps['placeholderColor'] = undefined;
export let labelColor: TextFieldProps['labelColor'] = undefined;
export let helperTextColor: TextFieldProps['helperTextColor'] = undefined;

// Tokens - Hover
export let hoverBackgroundColor: TextFieldProps['hoverBackgroundColor'] = undefined;
export let hoverBorderColor: TextFieldProps['hoverBorderColor'] = undefined;

// Tokens - Focus
export let focusBackgroundColor: TextFieldProps['focusBackgroundColor'] = undefined;
export let focusBorderColor: TextFieldProps['focusBorderColor'] = undefined;

// Tokens - Error
export let errorBackgroundColor: TextFieldProps['errorBackgroundColor'] = undefined;
export let errorTextColor: TextFieldProps['errorTextColor'] = undefined;
export let errorBorderColor: TextFieldProps['errorBorderColor'] = undefined;
export let errorLabelColor: TextFieldProps['errorLabelColor'] = undefined;
export let errorHelperTextColor: TextFieldProps['errorHelperTextColor'] = undefined;

// Tokens - Success
export let successBackgroundColor: TextFieldProps['successBackgroundColor'] = undefined;
export let successTextColor: TextFieldProps['successTextColor'] = undefined;
export let successBorderColor: TextFieldProps['successBorderColor'] = undefined;
export let successLabelColor: TextFieldProps['successLabelColor'] = undefined;
export let successHelperTextColor: TextFieldProps['successHelperTextColor'] = undefined;

// Tokens - Disabled
export let disabledBackgroundColor: TextFieldProps['disabledBackgroundColor'] = undefined;
export let disabledTextColor: TextFieldProps['disabledTextColor'] = undefined;
export let disabledBorderColor: TextFieldProps['disabledBorderColor'] = undefined;
export let disabledLabelColor: TextFieldProps['disabledLabelColor'] = undefined;

// Behavior
export let type: TextFieldProps['type'] = 'text';
export let disabled: TextFieldProps['disabled'] = false;
export let error: TextFieldProps['error'] = false;
export let success: TextFieldProps['success'] = false;
export let required: TextFieldProps['required'] = false;

// Layout
export let size: TextFieldProps['size'] = 'md';
export let fullWidth: TextFieldProps['fullWidth'] = false;
export let multiline: TextFieldProps['multiline'] = false;
export let rows: TextFieldProps['rows'] = 3;

// Styling
let className: TextFieldProps['class'] = undefined;
export { className as class };
export let style: TextFieldProps['style'] = undefined;

// Accessibility
export let ariaLabel: TextFieldProps['ariaLabel'] = undefined;
export let ariaDescribedby: TextFieldProps['ariaDescribedby'] = undefined;
export let testId: TextFieldProps['testId'] = undefined;

// Developer experience
export let showQualityWarnings: TextFieldProps['showQualityWarnings'] = true;

// ============================================================================
// STATE (Svelte-specific)
// ============================================================================

let isHovered = false;
let isFocused = false;

// ============================================================================
// TEXTFIELD CORE INTEGRATION
// ============================================================================

/**
 * Process text field logic via TextFieldCore.
 *
 * This reactive statement delegates ALL logic to TextFieldCore.processTextField().
 * NO logic duplication - pure delegation.
 */
$: textFieldOutput = TextFieldCore.processTextField({
  // Tokens
  tokens: {
    backgroundColor,
    textColor,
    borderColor,
    placeholderColor,
    labelColor,
    helperTextColor,
    hoverBackgroundColor,
    hoverBorderColor,
    focusBackgroundColor,
    focusBorderColor,
    errorBackgroundColor,
    errorTextColor,
    errorBorderColor,
    errorLabelColor,
    errorHelperTextColor,
    successBackgroundColor,
    successTextColor,
    successBorderColor,
    successLabelColor,
    successHelperTextColor,
    disabledBackgroundColor,
    disabledTextColor,
    disabledBorderColor,
    disabledLabelColor,
  },

  // Interaction state
  disabled,
  error,
  success,
  isHovered,
  isFocused,

  // Layout
  size,
  fullWidth,
  multiline,

  // Content
  label,
  helperText,

  // ARIA
  required,
  ariaLabel,
  ariaDescribedby,

  // Styles
  userStyles: style,

  // Dev mode
  showQualityWarnings,
  customClass: className,
});

// ============================================================================
// QUALITY WARNINGS (DEV MODE)
// ============================================================================

// Log quality warnings
$: if (textFieldOutput.qualityWarnings.length > 0) {
  textFieldOutput.qualityWarnings.forEach((warning) => {
    console.warn(`[TextField] ${warning.message}`, warning.details);
  });
}

// ============================================================================
// COMPUTED STYLES
// ============================================================================

$: containerStyles = [
  `width: ${textFieldOutput.styles.containerWidth}`,
  `display: ${textFieldOutput.styles.containerDisplay}`,
  `flex-direction: ${textFieldOutput.styles.containerFlexDirection}`,
  `gap: ${textFieldOutput.styles.containerGap}px`,
].join('; ');

$: inputStyles = [
  multiline ? 'height: auto' : `height: ${textFieldOutput.styles.inputHeight}px`,
  `padding-left: ${textFieldOutput.styles.inputPaddingLeft}px`,
  `padding-right: ${textFieldOutput.styles.inputPaddingRight}px`,
  `padding-top: ${textFieldOutput.styles.inputPaddingTop}px`,
  `padding-bottom: ${textFieldOutput.styles.inputPaddingBottom}px`,
  `font-size: ${textFieldOutput.styles.inputFontSize}px`,
  `font-weight: ${textFieldOutput.styles.inputFontWeight}`,
  `line-height: ${textFieldOutput.styles.inputLineHeight}`,
  `font-family: ${textFieldOutput.styles.inputFontFamily}`,
  `background-color: ${textFieldOutput.styles.inputBackgroundColor}`,
  `color: ${textFieldOutput.styles.inputColor}`,
  `border-radius: ${textFieldOutput.styles.inputBorderRadius}px`,
  `outline: ${textFieldOutput.styles.inputOutline}`,
  `cursor: ${textFieldOutput.styles.inputCursor}`,
  `transition: ${textFieldOutput.styles.inputTransition}`,
  textFieldOutput.styles.inputBorderWidth ? `border-width: ${textFieldOutput.styles.inputBorderWidth}px` : '',
  textFieldOutput.styles.inputBorderStyle ? `border-style: ${textFieldOutput.styles.inputBorderStyle}` : '',
  textFieldOutput.styles.inputBorderColor ? `border-color: ${textFieldOutput.styles.inputBorderColor}` : '',
].filter(Boolean).join('; ');

$: labelStyles = textFieldOutput.styles.labelColor ? [
  `font-size: ${textFieldOutput.styles.labelFontSize}px`,
  `font-weight: ${textFieldOutput.styles.labelFontWeight}`,
  `color: ${textFieldOutput.styles.labelColor}`,
  `margin-bottom: ${textFieldOutput.styles.labelMarginBottom}px`,
].join('; ') : '';

$: helperStyles = textFieldOutput.styles.helperColor ? [
  `font-size: ${textFieldOutput.styles.helperFontSize}px`,
  `color: ${textFieldOutput.styles.helperColor}`,
  `margin-top: ${textFieldOutput.styles.helperMarginTop}px`,
].join('; ') : '';

// ============================================================================
// EVENT HANDLERS (Svelte-specific)
// ============================================================================

const dispatch = createEventDispatcher<{
  input: string;
  focus: FocusEvent;
  blur: FocusEvent;
}>();

function handleInput(event: Event) {
  if (disabled) {
    return;
  }
  const target = event.target as HTMLInputElement | HTMLTextAreaElement;
  value = target.value;
  dispatch('input', value);
}

function handleMouseEnter() {
  if (disabled) {
    return;
  }
  isHovered = true;
}

function handleMouseLeave() {
  isHovered = false;
}

function handleFocus(event: FocusEvent) {
  if (disabled) {
    return;
  }
  isFocused = true;
  dispatch('focus', event);
}

function handleBlur(event: FocusEvent) {
  isFocused = false;
  dispatch('blur', event);
}
</script>

<div style={containerStyles} class={textFieldOutput.classNames}>
  <!-- Label (optional) -->
  {#if label}
    <label
      class="{CLASS_PREFIX}__label"
      style={labelStyles}
    >
      {label}
      {#if required}<span aria-label="required"> *</span>{/if}
    </label>
  {/if}

  <!-- Input (single-line) -->
  {#if !multiline}
    <input
      {type}
      {value}
      {placeholder}
      {disabled}
      {required}
      class="{CLASS_PREFIX}__input"
      style={inputStyles}
      aria-label={textFieldOutput.ariaAttrs['aria-label']}
      aria-describedby={textFieldOutput.ariaAttrs['aria-describedby']}
      aria-disabled={textFieldOutput.ariaAttrs['aria-disabled']}
      aria-invalid={textFieldOutput.ariaAttrs['aria-invalid']}
      aria-required={textFieldOutput.ariaAttrs['aria-required']}
      data-momoto-bg-quality={showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.qualityScore : undefined}
      data-momoto-bg-decision={showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined}
      data-momoto-text-quality={showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.qualityScore : undefined}
      data-momoto-wcag-ratio={showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.accessibility?.wcagRatio : undefined}
      data-testid={testId}
      on:input={handleInput}
      on:focus={handleFocus}
      on:blur={handleBlur}
      on:mouseenter={handleMouseEnter}
      on:mouseleave={handleMouseLeave}
    />
  {:else}
    <!-- Textarea (multiline) -->
    <textarea
      {value}
      {placeholder}
      {disabled}
      {required}
      {rows}
      class="{CLASS_PREFIX}__input {CLASS_PREFIX}__input--multiline"
      style={inputStyles}
      aria-label={textFieldOutput.ariaAttrs['aria-label']}
      aria-describedby={textFieldOutput.ariaAttrs['aria-describedby']}
      aria-disabled={textFieldOutput.ariaAttrs['aria-disabled']}
      aria-invalid={textFieldOutput.ariaAttrs['aria-invalid']}
      aria-required={textFieldOutput.ariaAttrs['aria-required']}
      data-momoto-bg-quality={showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.qualityScore : undefined}
      data-momoto-bg-decision={showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined}
      data-momoto-text-quality={showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.qualityScore : undefined}
      data-momoto-wcag-ratio={showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.accessibility?.wcagRatio : undefined}
      data-testid={testId}
      on:input={handleInput}
      on:focus={handleFocus}
      on:blur={handleBlur}
      on:mouseenter={handleMouseEnter}
      on:mouseleave={handleMouseLeave}
    />
  {/if}

  <!-- Helper text (optional) -->
  {#if helperText}
    <div
      class="{CLASS_PREFIX}__helper"
      style={helperStyles}
    >
      {helperText}
    </div>
  {/if}
</div>

<!--
CONTRACT COMPLIANCE:

✅ Zero logic duplication
   - ALL logic delegated to TextFieldCore.processTextField()
   - Adapter is THIN wrapper

✅ 100% token-driven
   - All colors from EnrichedToken (via TextFieldCore)
   - NO local color calculations

✅ State management via framework
   - Uses Svelte's reactive let for interaction state
   - TextFieldCore handles state determination

✅ Framework-specific concerns only
   - Template rendering (Svelte-specific)
   - Event handling (Svelte events → TextFieldCore)
   - Reactivity (Svelte $: reactive statements)

✅ Identical behavior to React/Vue
   - Same TextFieldCore
   - Same tokens
   - Same output

PATTERN: Exact copy of Button.svelte adapted for TextField

USAGE EXAMPLE:

```svelte
<script>
  import { TextField } from '@momoto/ui-adapters/svelte/textfield';

  let email = '';
  let inputBg = inputBackgroundToken;
  let inputText = inputTextToken;

  function handleInput(event) {
    console.log('Value:', event.detail);
  }
</script>

<TextField
  label="Email"
  bind:value={email}
  backgroundColor={inputBg}
  textColor={inputText}
  placeholder="Enter your email"
  type="email"
  on:input={handleInput}
/>
```
-->
