// src/adapters/vue/select/Select.vue
<script setup lang="ts" generic="T = string">
/**
 * @fileoverview Vue Select Adapter
 *
 * FASE 15.4: Component Expansion - Select
 *
 * Vue adapter for SelectCore.
 * This is a THIN wrapper that delegates all logic to SelectCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to SelectCore)
 * - ✅ 100% token-driven (via SelectCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/vue/select
 * @version 1.0.0
 */

import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import { SelectCore, CLASS_PREFIX } from '../../core/select';
import type { SelectProps } from './types';
import type { SelectOption } from '../../core/select';

// ──────────────────────────────────────────────────────────────────────────
// PROPS
// ──────────────────────────────────────────────────────────────────────────

const props = withDefaults(defineProps<SelectProps<T>>(), {
  disabled: false,
  required: false,
  error: false,
  size: 'md',
  showQualityWarnings: true,
});

// ──────────────────────────────────────────────────────────────────────────
// EMITS
// ──────────────────────────────────────────────────────────────────────────

const emit = defineEmits<{
  'update:value': [value: T | null];
}>();

// ──────────────────────────────────────────────────────────────────────────
// STATE (Vue-specific)
// ──────────────────────────────────────────────────────────────────────────

const isOpen = ref(false);
const isHovered = ref(false);
const isFocused = ref(false);
const highlightedValue = ref<T | null>(null);
const containerRef = ref<HTMLDivElement | null>(null);

// ──────────────────────────────────────────────────────────────────────────
// SELECT CORE INTEGRATION
// ──────────────────────────────────────────────────────────────────────────

const selectOutput = computed(() =>
  SelectCore.processSelect<T>({
    tokens: {
      backgroundColor: props.backgroundColor,
      borderColor: props.borderColor,
      textColor: props.textColor,
      placeholderColor: props.placeholderColor,
      iconColor: props.iconColor,
      hoverBackgroundColor: props.hoverBackgroundColor,
      hoverBorderColor: props.hoverBorderColor,
      hoverTextColor: props.hoverTextColor,
      hoverIconColor: props.hoverIconColor,
      focusBackgroundColor: props.focusBackgroundColor,
      focusBorderColor: props.focusBorderColor,
      focusTextColor: props.focusTextColor,
      focusOutlineColor: props.focusOutlineColor,
      focusIconColor: props.focusIconColor,
      openBackgroundColor: props.openBackgroundColor,
      openBorderColor: props.openBorderColor,
      openTextColor: props.openTextColor,
      openOutlineColor: props.openOutlineColor,
      openIconColor: props.openIconColor,
      openHoverBackgroundColor: props.openHoverBackgroundColor,
      openHoverBorderColor: props.openHoverBorderColor,
      openFocusBackgroundColor: props.openFocusBackgroundColor,
      openFocusBorderColor: props.openFocusBorderColor,
      openFocusOutlineColor: props.openFocusOutlineColor,
      disabledBackgroundColor: props.disabledBackgroundColor,
      disabledBorderColor: props.disabledBorderColor,
      disabledTextColor: props.disabledTextColor,
      disabledPlaceholderColor: props.disabledPlaceholderColor,
      disabledLabelColor: props.disabledLabelColor,
      disabledIconColor: props.disabledIconColor,
      errorBackgroundColor: props.errorBackgroundColor,
      errorBorderColor: props.errorBorderColor,
      errorTextColor: props.errorTextColor,
      errorMessageColor: props.errorMessageColor,
      errorIconColor: props.errorIconColor,
      errorHoverBackgroundColor: props.errorHoverBackgroundColor,
      errorHoverBorderColor: props.errorHoverBorderColor,
      errorFocusBackgroundColor: props.errorFocusBackgroundColor,
      errorFocusBorderColor: props.errorFocusBorderColor,
      errorFocusOutlineColor: props.errorFocusOutlineColor,
      labelColor: props.labelColor,
      helperTextColor: props.helperTextColor,
      dropdownBackgroundColor: props.dropdownBackgroundColor,
      dropdownBorderColor: props.dropdownBorderColor,
      dropdownShadowColor: props.dropdownShadowColor,
      optionTextColor: props.optionTextColor,
      optionHoverBackgroundColor: props.optionHoverBackgroundColor,
      optionHoverTextColor: props.optionHoverTextColor,
      optionSelectedBackgroundColor: props.optionSelectedBackgroundColor,
      optionSelectedTextColor: props.optionSelectedTextColor,
      optionDisabledTextColor: props.optionDisabledTextColor,
      optionDisabledBackgroundColor: props.optionDisabledBackgroundColor,
    },
    options: props.options,
    value: props.value,
    placeholder: props.placeholder,
    isOpen: isOpen.value,
    highlightedValue: highlightedValue.value,
    disabled: props.disabled,
    isHovered: isHovered.value,
    isFocused: isFocused.value,
    hasError: props.error,
    size: props.size,
    label: props.label,
    helperText: props.helperText,
    errorMessage: props.errorMessage,
    required: props.required,
    ariaLabel: props.ariaLabel,
    ariaDescribedby: props.ariaDescribedby,
    ariaLabelledby: props.ariaLabelledby,
    userStyles: props.style,
    customClass: props.class,
    showQualityWarnings: props.showQualityWarnings,
  })
);

// ──────────────────────────────────────────────────────────────────────────
// QUALITY WARNINGS
// ──────────────────────────────────────────────────────────────────────────

watch(
  () => selectOutput.value.qualityWarnings,
  (warnings) => {
    if (warnings.length > 0) {
      warnings.forEach((warning) => {
        console.warn(`[Select] ${warning.message}`, warning.details);
      });
    }
  }
);

// ──────────────────────────────────────────────────────────────────────────
// CLOSE ON OUTSIDE CLICK
// ──────────────────────────────────────────────────────────────────────────

const handleClickOutside = (event: MouseEvent) => {
  if (containerRef.value && !containerRef.value.contains(event.target as Node)) {
    isOpen.value = false;
  }
};

watch(isOpen, (newIsOpen) => {
  if (newIsOpen) {
    document.addEventListener('mousedown', handleClickOutside);
  } else {
    document.removeEventListener('mousedown', handleClickOutside);
  }
});

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});

// ──────────────────────────────────────────────────────────────────────────
// EVENT HANDLERS
// ──────────────────────────────────────────────────────────────────────────

const handleFieldClick = () => {
  if (props.disabled) return;
  isOpen.value = !isOpen.value;
};

const handleOptionClick = (optionValue: T, optionDisabled?: boolean) => {
  if (props.disabled || optionDisabled) return;
  emit('update:value', optionValue);
  isOpen.value = false;
};

// ──────────────────────────────────────────────────────────────────────────
// HELPERS
// ──────────────────────────────────────────────────────────────────────────

const getOptionStyle = (option: SelectOption<T>, isHighlighted: boolean) => {
  const isSelected = option.value === props.value;
  let bgColor = 'transparent';
  let txtColor = selectOutput.value.styles.optionTextColor;

  if (option.disabled) {
    bgColor = selectOutput.value.styles.optionDisabledBackgroundColor;
    txtColor = selectOutput.value.styles.optionDisabledTextColor;
  } else if (isSelected) {
    bgColor = selectOutput.value.styles.optionSelectedBackgroundColor;
    txtColor = selectOutput.value.styles.optionSelectedTextColor;
  } else if (isHighlighted) {
    bgColor = selectOutput.value.styles.optionHoverBackgroundColor;
    txtColor = selectOutput.value.styles.optionHoverTextColor;
  }

  return {
    padding: `${selectOutput.value.styles.optionPaddingY}px ${selectOutput.value.styles.optionPaddingX}px`,
    fontSize: `${selectOutput.value.styles.optionFontSize}px`,
    color: txtColor,
    backgroundColor: bgColor,
    cursor: option.disabled ? selectOutput.value.styles.optionDisabledCursor : selectOutput.value.styles.optionCursor,
    transition: selectOutput.value.styles.optionTransition,
    opacity: option.disabled ? selectOutput.value.styles.optionDisabledOpacity : 1,
  };
};

const displayHelperText = computed(() =>
  props.error && props.errorMessage ? props.errorMessage : props.helperText
);
</script>

<template>
  <div ref="containerRef" :class="selectOutput.classNames" :style="{
    display: selectOutput.styles.containerDisplay,
    flexDirection: selectOutput.styles.containerFlexDirection,
    gap: `${selectOutput.styles.containerGap}px`,
  }">
    <!-- Label -->
    <label v-if="label" :class="`${CLASS_PREFIX}__label`" :style="{
      display: selectOutput.styles.labelDisplay,
      fontSize: `${selectOutput.styles.labelFontSize}px`,
      color: selectOutput.styles.labelColor,
      fontWeight: selectOutput.styles.labelFontWeight,
    }">
      {{ label }}<template v-if="required"> *</template>
    </label>

    <!-- Field -->
    <div
      :role="selectOutput.ariaAttrs.role"
      :aria-expanded="selectOutput.ariaAttrs['aria-expanded']"
      :aria-controls="selectOutput.ariaAttrs['aria-controls']"
      :aria-activedescendant="selectOutput.ariaAttrs['aria-activedescendant']"
      :aria-disabled="selectOutput.ariaAttrs['aria-disabled']"
      :aria-required="selectOutput.ariaAttrs['aria-required']"
      :aria-invalid="selectOutput.ariaAttrs['aria-invalid']"
      :aria-label="selectOutput.ariaAttrs['aria-label']"
      :aria-describedby="selectOutput.ariaAttrs['aria-describedby']"
      :aria-labelledby="selectOutput.ariaAttrs['aria-labelledby']"
      :tabindex="disabled ? -1 : 0"
      :class="`${CLASS_PREFIX}__field`"
      :data-testid="testId"
      :style="{
        position: selectOutput.styles.fieldPosition,
        display: selectOutput.styles.fieldDisplay,
        alignItems: selectOutput.styles.fieldAlignItems,
        justifyContent: selectOutput.styles.fieldJustifyContent,
        height: `${selectOutput.styles.fieldHeight}px`,
        padding: `0 ${selectOutput.styles.fieldPaddingX}px`,
        backgroundColor: selectOutput.styles.fieldBackgroundColor,
        borderWidth: `${selectOutput.styles.fieldBorderWidth}px`,
        borderStyle: selectOutput.styles.fieldBorderStyle,
        borderColor: selectOutput.styles.fieldBorderColor,
        borderRadius: `${selectOutput.styles.fieldBorderRadius}px`,
        color: selectOutput.styles.fieldTextColor,
        fontSize: `${selectOutput.styles.fieldFontSize}px`,
        cursor: selectOutput.styles.fieldCursor,
        transition: selectOutput.styles.fieldTransition,
        opacity: selectOutput.styles.fieldOpacity,
        outline: selectOutput.styles.outlineColor ? `${selectOutput.styles.outlineWidth}px solid ${selectOutput.styles.outlineColor}` : 'none',
        outlineOffset: `${selectOutput.styles.outlineOffset}px`,
      }"
      @click="handleFieldClick"
      @mouseenter="isHovered = true"
      @mouseleave="isHovered = false"
      @focus="isFocused = true"
      @blur="isFocused = false"
    >
      <!-- Display value -->
      <span :class="`${CLASS_PREFIX}__value`" :style="{
        color: selectOutput.selectedOption ? selectOutput.styles.fieldTextColor : selectOutput.styles.placeholderColor,
        flex: 1,
      }">
        {{ selectOutput.displayValue }}
      </span>

      <!-- Chevron icon -->
      <svg :class="`${CLASS_PREFIX}__icon`" :style="{
        width: `${selectOutput.styles.iconSize}px`,
        height: `${selectOutput.styles.iconSize}px`,
        color: selectOutput.styles.iconColor,
        transform: selectOutput.styles.iconTransform,
        transition: selectOutput.styles.fieldTransition,
        flexShrink: 0,
      }" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
        <path d="M5 7.5l5 5 5-5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </svg>

      <!-- Dropdown -->
      <div v-if="isOpen && !disabled" :id="selectOutput.ariaAttrs['aria-controls']" role="listbox" :class="`${CLASS_PREFIX}__dropdown`" :style="{
        position: selectOutput.styles.dropdownPosition,
        top: selectOutput.styles.dropdownTop,
        left: selectOutput.styles.dropdownLeft,
        right: selectOutput.styles.dropdownRight,
        zIndex: selectOutput.styles.dropdownZIndex,
        backgroundColor: selectOutput.styles.dropdownBackgroundColor,
        borderWidth: `${selectOutput.styles.dropdownBorderWidth}px`,
        borderStyle: selectOutput.styles.dropdownBorderStyle,
        borderColor: selectOutput.styles.dropdownBorderColor,
        borderRadius: `${selectOutput.styles.dropdownBorderRadius}px`,
        boxShadow: selectOutput.styles.dropdownBoxShadow,
        maxHeight: `${selectOutput.styles.dropdownMaxHeight}px`,
        overflowY: selectOutput.styles.dropdownOverflowY,
      }">
        <div
          v-for="option in options"
          :key="String(option.value)"
          :id="`momoto-select-option-${String(option.value)}`"
          role="option"
          :aria-selected="option.value === value"
          :aria-disabled="option.disabled"
          :class="`${CLASS_PREFIX}__option`"
          :style="getOptionStyle(option, highlightedValue === option.value)"
          @click="handleOptionClick(option.value, option.disabled)"
          @mouseenter="highlightedValue = option.value"
        >
          {{ option.label }}
        </div>
      </div>
    </div>

    <!-- Helper text -->
    <span v-if="displayHelperText" :class="`${CLASS_PREFIX}__helper`" :style="{
      display: selectOutput.styles.helperDisplay,
      fontSize: `${selectOutput.styles.helperFontSize}px`,
      color: selectOutput.styles.helperColor,
    }">
      {{ displayHelperText }}
    </span>
  </div>
</template>

// src/adapters/angular/select/select.component.ts
/**
 * @fileoverview Angular Select Component
 *
 * FASE 15.4: Component Expansion - Select
 *
 * Angular adapter for SelectCore.
 * This is a THIN wrapper that delegates all logic to SelectCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to SelectCore)
 * - ✅ 100% token-driven (via SelectCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/angular/select
 * @version 1.0.0
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnChanges,
  SimpleChanges,
  HostListener,
  ElementRef,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { SelectCore, CLASS_PREFIX } from '../../core/select';
import type {
  SelectCoreOutput,
  SelectSize,
  SelectStyles,
  SelectOption,
} from '../../core/select';
import type { EnrichedToken } from '../../../domain/tokens/value-objects/EnrichedToken';

@Component({
  selector: 'momoto-select',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.css'],
})
export class SelectComponent<T = string> implements OnChanges {
  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - OPTIONS & VALUE
  // ──────────────────────────────────────────────────────────────────────────

  @Input({ required: true }) options!: SelectOption<T>[];
  @Input({ required: true }) value!: T | null;
  @Input() placeholder?: string;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - TOKENS FIELD BASE
  // ──────────────────────────────────────────────────────────────────────────

  @Input({ required: true }) backgroundColor!: EnrichedToken;
  @Input({ required: true }) borderColor!: EnrichedToken;
  @Input({ required: true }) textColor!: EnrichedToken;
  @Input() placeholderColor?: EnrichedToken;
  @Input() iconColor?: EnrichedToken;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - TOKENS FIELD HOVER/FOCUS/OPEN
  // ──────────────────────────────────────────────────────────────────────────

  @Input() hoverBackgroundColor?: EnrichedToken;
  @Input() hoverBorderColor?: EnrichedToken;
  @Input() hoverTextColor?: EnrichedToken;
  @Input() hoverIconColor?: EnrichedToken;
  @Input() focusBackgroundColor?: EnrichedToken;
  @Input() focusBorderColor?: EnrichedToken;
  @Input() focusTextColor?: EnrichedToken;
  @Input() focusOutlineColor?: EnrichedToken;
  @Input() focusIconColor?: EnrichedToken;
  @Input() openBackgroundColor?: EnrichedToken;
  @Input() openBorderColor?: EnrichedToken;
  @Input() openTextColor?: EnrichedToken;
  @Input() openOutlineColor?: EnrichedToken;
  @Input() openIconColor?: EnrichedToken;
  @Input() openHoverBackgroundColor?: EnrichedToken;
  @Input() openHoverBorderColor?: EnrichedToken;
  @Input() openFocusBackgroundColor?: EnrichedToken;
  @Input() openFocusBorderColor?: EnrichedToken;
  @Input() openFocusOutlineColor?: EnrichedToken;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - TOKENS DISABLED/ERROR
  // ──────────────────────────────────────────────────────────────────────────

  @Input() disabledBackgroundColor?: EnrichedToken;
  @Input() disabledBorderColor?: EnrichedToken;
  @Input() disabledTextColor?: EnrichedToken;
  @Input() disabledPlaceholderColor?: EnrichedToken;
  @Input() disabledLabelColor?: EnrichedToken;
  @Input() disabledIconColor?: EnrichedToken;
  @Input() errorBackgroundColor?: EnrichedToken;
  @Input() errorBorderColor?: EnrichedToken;
  @Input() errorTextColor?: EnrichedToken;
  @Input() errorMessageColor?: EnrichedToken;
  @Input() errorIconColor?: EnrichedToken;
  @Input() errorHoverBackgroundColor?: EnrichedToken;
  @Input() errorHoverBorderColor?: EnrichedToken;
  @Input() errorFocusBackgroundColor?: EnrichedToken;
  @Input() errorFocusBorderColor?: EnrichedToken;
  @Input() errorFocusOutlineColor?: EnrichedToken;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - TOKENS LABEL/HELPER
  // ──────────────────────────────────────────────────────────────────────────

  @Input() labelColor?: EnrichedToken;
  @Input() helperTextColor?: EnrichedToken;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - TOKENS DROPDOWN
  // ──────────────────────────────────────────────────────────────────────────

  @Input({ required: true }) dropdownBackgroundColor!: EnrichedToken;
  @Input() dropdownBorderColor?: EnrichedToken;
  @Input() dropdownShadowColor?: EnrichedToken;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - TOKENS OPTIONS
  // ──────────────────────────────────────────────────────────────────────────

  @Input({ required: true }) optionTextColor!: EnrichedToken;
  @Input() optionHoverBackgroundColor?: EnrichedToken;
  @Input() optionHoverTextColor?: EnrichedToken;
  @Input() optionSelectedBackgroundColor?: EnrichedToken;
  @Input() optionSelectedTextColor?: EnrichedToken;
  @Input() optionDisabledTextColor?: EnrichedToken;
  @Input() optionDisabledBackgroundColor?: EnrichedToken;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - BEHAVIOR
  // ──────────────────────────────────────────────────────────────────────────

  @Input() disabled = false;
  @Input() required = false;
  @Input() error = false;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - LAYOUT
  // ──────────────────────────────────────────────────────────────────────────

  @Input() size: SelectSize = 'md';

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - CONTENT
  // ──────────────────────────────────────────────────────────────────────────

  @Input() label?: string;
  @Input() helperText?: string;
  @Input() errorMessage?: string;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - STYLING
  // ──────────────────────────────────────────────────────────────────────────

  @Input() customClass?: string;
  @Input() customStyle?: Partial<SelectStyles>;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - ACCESSIBILITY
  // ──────────────────────────────────────────────────────────────────────────

  @Input() ariaLabel?: string;
  @Input() ariaDescribedby?: string;
  @Input() ariaLabelledby?: string;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - TESTING
  // ──────────────────────────────────────────────────────────────────────────

  @Input() testId?: string;

  // ──────────────────────────────────────────────────────────────────────────
  // INPUTS - DEVELOPER EXPERIENCE
  // ──────────────────────────────────────────────────────────────────────────

  @Input() showQualityWarnings = true;

  // ──────────────────────────────────────────────────────────────────────────
  // OUTPUTS
  // ──────────────────────────────────────────────────────────────────────────

  @Output() valueChange = new EventEmitter<T | null>();

  // ──────────────────────────────────────────────────────────────────────────
  // STATE (Angular-specific)
  // ──────────────────────────────────────────────────────────────────────────

  isOpen = false;
  isHovered = false;
  isFocused = false;
  highlightedValue: T | null = null;

  // ──────────────────────────────────────────────────────────────────────────
  // SELECT CORE OUTPUT
  // ──────────────────────────────────────────────────────────────────────────

  selectOutput!: SelectCoreOutput<T>;

  // ──────────────────────────────────────────────────────────────────────────
  // CONSTANTS
  // ──────────────────────────────────────────────────────────────────────────

  CLASS_PREFIX = CLASS_PREFIX;

  // ──────────────────────────────────────────────────────────────────────────
  // CONSTRUCTOR
  // ──────────────────────────────────────────────────────────────────────────

  constructor(private elementRef: ElementRef) {}

  // ──────────────────────────────────────────────────────────────────────────
  // LIFECYCLE - ON CHANGES
  // ──────────────────────────────────────────────────────────────────────────

  ngOnChanges(changes: SimpleChanges): void {
    this.updateSelectOutput();

    if (this.selectOutput.qualityWarnings.length > 0) {
      this.selectOutput.qualityWarnings.forEach((warning) => {
        console.warn(`[Select] ${warning.message}`, warning.details);
      });
    }
  }

  // ──────────────────────────────────────────────────────────────────────────
  // CLOSE ON OUTSIDE CLICK
  // ──────────────────────────────────────────────────────────────────────────

  @HostListener('document:mousedown', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (this.isOpen && !this.elementRef.nativeElement.contains(event.target)) {
      this.isOpen = false;
      this.updateSelectOutput();
    }
  }

  // ──────────────────────────────────────────────────────────────────────────
  // UPDATE SELECT OUTPUT
  // ──────────────────────────────────────────────────────────────────────────

  private updateSelectOutput(): void {
    this.selectOutput = SelectCore.processSelect<T>({
      tokens: {
        backgroundColor: this.backgroundColor,
        borderColor: this.borderColor,
        textColor: this.textColor,
        placeholderColor: this.placeholderColor,
        iconColor: this.iconColor,
        hoverBackgroundColor: this.hoverBackgroundColor,
        hoverBorderColor: this.hoverBorderColor,
        hoverTextColor: this.hoverTextColor,
        hoverIconColor: this.hoverIconColor,
        focusBackgroundColor: this.focusBackgroundColor,
        focusBorderColor: this.focusBorderColor,
        focusTextColor: this.focusTextColor,
        focusOutlineColor: this.focusOutlineColor,
        focusIconColor: this.focusIconColor,
        openBackgroundColor: this.openBackgroundColor,
        openBorderColor: this.openBorderColor,
        openTextColor: this.openTextColor,
        openOutlineColor: this.openOutlineColor,
        openIconColor: this.openIconColor,
        openHoverBackgroundColor: this.openHoverBackgroundColor,
        openHoverBorderColor: this.openHoverBorderColor,
        openFocusBackgroundColor: this.openFocusBackgroundColor,
        openFocusBorderColor: this.openFocusBorderColor,
        openFocusOutlineColor: this.openFocusOutlineColor,
        disabledBackgroundColor: this.disabledBackgroundColor,
        disabledBorderColor: this.disabledBorderColor,
        disabledTextColor: this.disabledTextColor,
        disabledPlaceholderColor: this.disabledPlaceholderColor,
        disabledLabelColor: this.disabledLabelColor,
        disabledIconColor: this.disabledIconColor,
        errorBackgroundColor: this.errorBackgroundColor,
        errorBorderColor: this.errorBorderColor,
        errorTextColor: this.errorTextColor,
        errorMessageColor: this.errorMessageColor,
        errorIconColor: this.errorIconColor,
        errorHoverBackgroundColor: this.errorHoverBackgroundColor,
        errorHoverBorderColor: this.errorHoverBorderColor,
        errorFocusBackgroundColor: this.errorFocusBackgroundColor,
        errorFocusBorderColor: this.errorFocusBorderColor,
        errorFocusOutlineColor: this.errorFocusOutlineColor,
        labelColor: this.labelColor,
        helperTextColor: this.helperTextColor,
        dropdownBackgroundColor: this.dropdownBackgroundColor,
        dropdownBorderColor: this.dropdownBorderColor,
        dropdownShadowColor: this.dropdownShadowColor,
        optionTextColor: this.optionTextColor,
        optionHoverBackgroundColor: this.optionHoverBackgroundColor,
        optionHoverTextColor: this.optionHoverTextColor,
        optionSelectedBackgroundColor: this.optionSelectedBackgroundColor,
        optionSelectedTextColor: this.optionSelectedTextColor,
        optionDisabledTextColor: this.optionDisabledTextColor,
        optionDisabledBackgroundColor: this.optionDisabledBackgroundColor,
      },
      options: this.options,
      value: this.value,
      placeholder: this.placeholder,
      isOpen: this.isOpen,
      highlightedValue: this.highlightedValue,
      disabled: this.disabled,
      isHovered: this.isHovered,
      isFocused: this.isFocused,
      hasError: this.error,
      size: this.size,
      label: this.label,
      helperText: this.helperText,
      errorMessage: this.errorMessage,
      required: this.required,
      ariaLabel: this.ariaLabel,
      ariaDescribedby: this.ariaDescribedby,
      ariaLabelledby: this.ariaLabelledby,
      userStyles: this.customStyle,
      customClass: this.customClass,
      showQualityWarnings: this.showQualityWarnings,
    });
  }

  // ──────────────────────────────────────────────────────────────────────────
  // STYLE GETTERS
  // ──────────────────────────────────────────────────────────────────────────

  getContainerStyle(): Record<string, string> {
    return {
      display: this.selectOutput.styles.containerDisplay,
      flexDirection: this.selectOutput.styles.containerFlexDirection,
      gap: `${this.selectOutput.styles.containerGap}px`,
    };
  }

  getFieldStyle(): Record<string, string> {
    return {
      position: this.selectOutput.styles.fieldPosition,
      display: this.selectOutput.styles.fieldDisplay,
      alignItems: this.selectOutput.styles.fieldAlignItems,
      justifyContent: this.selectOutput.styles.fieldJustifyContent,
      height: `${this.selectOutput.styles.fieldHeight}px`,
      padding: `0 ${this.selectOutput.styles.fieldPaddingX}px`,
      backgroundColor: this.selectOutput.styles.fieldBackgroundColor,
      borderWidth: `${this.selectOutput.styles.fieldBorderWidth}px`,
      borderStyle: this.selectOutput.styles.fieldBorderStyle,
      borderColor: this.selectOutput.styles.fieldBorderColor,
      borderRadius: `${this.selectOutput.styles.fieldBorderRadius}px`,
      color: this.selectOutput.styles.fieldTextColor,
      fontSize: `${this.selectOutput.styles.fieldFontSize}px`,
      cursor: this.selectOutput.styles.fieldCursor,
      transition: this.selectOutput.styles.fieldTransition,
      opacity: this.selectOutput.styles.fieldOpacity.toString(),
      outline: this.selectOutput.styles.outlineColor
        ? `${this.selectOutput.styles.outlineWidth}px solid ${this.selectOutput.styles.outlineColor}`
        : 'none',
      outlineOffset: `${this.selectOutput.styles.outlineOffset}px`,
    };
  }

  getIconStyle(): Record<string, string> {
    return {
      width: `${this.selectOutput.styles.iconSize}px`,
      height: `${this.selectOutput.styles.iconSize}px`,
      color: this.selectOutput.styles.iconColor,
      transform: this.selectOutput.styles.iconTransform,
      transition: this.selectOutput.styles.fieldTransition,
      flexShrink: '0',
    };
  }

  getLabelStyle(): Record<string, string> {
    return {
      display: this.selectOutput.styles.labelDisplay,
      fontSize: `${this.selectOutput.styles.labelFontSize}px`,
      color: this.selectOutput.styles.labelColor,
      fontWeight: this.selectOutput.styles.labelFontWeight.toString(),
    };
  }

  getHelperStyle(): Record<string, string> {
    return {
      display: this.selectOutput.styles.helperDisplay,
      fontSize: `${this.selectOutput.styles.helperFontSize}px`,
      color: this.selectOutput.styles.helperColor,
    };
  }

  getDropdownStyle(): Record<string, string> {
    return {
      position: this.selectOutput.styles.dropdownPosition,
      top: this.selectOutput.styles.dropdownTop,
      left: this.selectOutput.styles.dropdownLeft,
      right: this.selectOutput.styles.dropdownRight,
      zIndex: this.selectOutput.styles.dropdownZIndex.toString(),
      backgroundColor: this.selectOutput.styles.dropdownBackgroundColor,
      borderWidth: `${this.selectOutput.styles.dropdownBorderWidth}px`,
      borderStyle: this.selectOutput.styles.dropdownBorderStyle,
      borderColor: this.selectOutput.styles.dropdownBorderColor,
      borderRadius: `${this.selectOutput.styles.dropdownBorderRadius}px`,
      boxShadow: this.selectOutput.styles.dropdownBoxShadow,
      maxHeight: `${this.selectOutput.styles.dropdownMaxHeight}px`,
      overflowY: this.selectOutput.styles.dropdownOverflowY,
    };
  }

  getOptionStyle(option: SelectOption<T>): Record<string, string> {
    const isSelected = option.value === this.value;
    const isHighlighted = this.highlightedValue === option.value;
    let bgColor = 'transparent';
    let txtColor = this.selectOutput.styles.optionTextColor;

    if (option.disabled) {
      bgColor = this.selectOutput.styles.optionDisabledBackgroundColor;
      txtColor = this.selectOutput.styles.optionDisabledTextColor;
    } else if (isSelected) {
      bgColor = this.selectOutput.styles.optionSelectedBackgroundColor;
      txtColor = this.selectOutput.styles.optionSelectedTextColor;
    } else if (isHighlighted) {
      bgColor = this.selectOutput.styles.optionHoverBackgroundColor;
      txtColor = this.selectOutput.styles.optionHoverTextColor;
    }

    return {
      padding: `${this.selectOutput.styles.optionPaddingY}px ${this.selectOutput.styles.optionPaddingX}px`,
      fontSize: `${this.selectOutput.styles.optionFontSize}px`,
      color: txtColor,
      backgroundColor: bgColor,
      cursor: option.disabled
        ? this.selectOutput.styles.optionDisabledCursor
        : this.selectOutput.styles.optionCursor,
      transition: this.selectOutput.styles.optionTransition,
      opacity: option.disabled
        ? this.selectOutput.styles.optionDisabledOpacity.toString()
        : '1',
    };
  }

  // ──────────────────────────────────────────────────────────────────────────
  // EVENT HANDLERS
  // ──────────────────────────────────────────────────────────────────────────

  onFieldClick(): void {
    if (this.disabled) return;
    this.isOpen = !this.isOpen;
    this.updateSelectOutput();
  }

  onOptionClick(optionValue: T, optionDisabled?: boolean): void {
    if (this.disabled || optionDisabled) return;
    this.valueChange.emit(optionValue);
    this.isOpen = false;
    this.updateSelectOutput();
  }

  onMouseEnter(): void {
    if (this.disabled) return;
    this.isHovered = true;
    this.updateSelectOutput();
  }

  onMouseLeave(): void {
    this.isHovered = false;
    this.updateSelectOutput();
  }

  onFocus(): void {
    if (this.disabled) return;
    this.isFocused = true;
    this.updateSelectOutput();
  }

  onBlur(): void {
    this.isFocused = false;
    this.updateSelectOutput();
  }

  onOptionMouseEnter(optionValue: T): void {
    this.highlightedValue = optionValue;
  }

  // ──────────────────────────────────────────────────────────────────────────
  // HELPERS
  // ──────────────────────────────────────────────────────────────────────────

  get displayHelperText(): string | undefined {
    return this.error && this.errorMessage ? this.errorMessage : this.helperText;
  }

  get classNames(): string {
    return this.selectOutput.classNames;
  }

  get ariaAttrs() {
    return this.selectOutput.ariaAttrs;
  }

  // ──────────────────────────────────────────────────────────────────────────
  // TRACK BY
  // ──────────────────────────────────────────────────────────────────────────

  trackByValue(index: number, option: SelectOption<T>): T {
    return option.value;
  }
}
