// adapters/angular/checkbox/checkbox.component.ts
/**
 * @fileoverview Angular Checkbox Adapter
 *
 * FASE 15: Component Expansion
 *
 * Angular adapter for CheckboxCore.
 * This is a THIN wrapper that delegates all logic to CheckboxCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to CheckboxCore)
 * - ✅ 100% token-driven (via CheckboxCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/angular/checkbox
 * @version 1.0.0
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnChanges,
  SimpleChanges,
  ChangeDetectionStrategy,
  ViewChild,
  ElementRef,
  AfterViewInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { CheckboxCore, CLASS_PREFIX } from '../../core/checkbox';
import type {
  CheckboxSize,
  CheckboxStyles,
  ResolvedCheckboxTokens,
  CheckboxState,
  SizeConfig,
  QualityWarning,
  ARIAAttributes,
} from '../../core/checkbox/checkboxCore.types';
import type { EnrichedToken } from '../../../domain/tokens/value-objects/EnrichedToken';

@Component({
  selector: 'momoto-checkbox',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './checkbox.component.html',
  styleUrls: ['./checkbox.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CheckboxComponent implements OnChanges, AfterViewInit {
  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - CHECK STATE
  // ══════════════════════════════════════════════════════════════════════════

  @Input() checked = false;
  @Input() indeterminate = false;
  @Input() label?: string;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (BASE)
  // ══════════════════════════════════════════════════════════════════════════

  @Input({ required: true }) backgroundColor!: EnrichedToken;
  @Input({ required: true }) borderColor!: EnrichedToken;
  @Input({ required: true }) checkColor!: EnrichedToken;
  @Input() labelColor?: EnrichedToken | null;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (HOVER)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() hoverBackgroundColor?: EnrichedToken;
  @Input() hoverBorderColor?: EnrichedToken;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (FOCUS)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() focusBackgroundColor?: EnrichedToken;
  @Input() focusBorderColor?: EnrichedToken;
  @Input() focusOutlineColor?: EnrichedToken;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (CHECKED)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() checkedBackgroundColor?: EnrichedToken;
  @Input() checkedBorderColor?: EnrichedToken;
  @Input() checkedCheckColor?: EnrichedToken;

  @Input() checkedHoverBackgroundColor?: EnrichedToken;
  @Input() checkedHoverBorderColor?: EnrichedToken;
  @Input() checkedHoverCheckColor?: EnrichedToken;

  @Input() checkedFocusBackgroundColor?: EnrichedToken;
  @Input() checkedFocusBorderColor?: EnrichedToken;
  @Input() checkedFocusCheckColor?: EnrichedToken;
  @Input() checkedFocusOutlineColor?: EnrichedToken;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (INDETERMINATE)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() indeterminateBackgroundColor?: EnrichedToken;
  @Input() indeterminateBorderColor?: EnrichedToken;
  @Input() indeterminateCheckColor?: EnrichedToken;

  @Input() indeterminateHoverBackgroundColor?: EnrichedToken;
  @Input() indeterminateHoverBorderColor?: EnrichedToken;
  @Input() indeterminateHoverCheckColor?: EnrichedToken;

  @Input() indeterminateFocusBackgroundColor?: EnrichedToken;
  @Input() indeterminateFocusBorderColor?: EnrichedToken;
  @Input() indeterminateFocusCheckColor?: EnrichedToken;
  @Input() indeterminateFocusOutlineColor?: EnrichedToken;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - TOKENS (DISABLED)
  // ══════════════════════════════════════════════════════════════════════════

  @Input() disabledBackgroundColor?: EnrichedToken;
  @Input() disabledBorderColor?: EnrichedToken;
  @Input() disabledCheckColor?: EnrichedToken;
  @Input() disabledLabelColor?: EnrichedToken;

  @Input() checkedDisabledBackgroundColor?: EnrichedToken;
  @Input() checkedDisabledBorderColor?: EnrichedToken;
  @Input() checkedDisabledCheckColor?: EnrichedToken;

  @Input() indeterminateDisabledBackgroundColor?: EnrichedToken;
  @Input() indeterminateDisabledBorderColor?: EnrichedToken;
  @Input() indeterminateDisabledCheckColor?: EnrichedToken;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - BEHAVIOR
  // ══════════════════════════════════════════════════════════════════════════

  @Input() disabled = false;
  @Input() required = false;
  @Input() invalid = false;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - LAYOUT
  // ══════════════════════════════════════════════════════════════════════════

  @Input() size: CheckboxSize = 'md';

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - STYLING
  // ══════════════════════════════════════════════════════════════════════════

  @Input() customClass?: string;
  @Input() customStyle?: Partial<CheckboxStyles>;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - ACCESSIBILITY
  // ══════════════════════════════════════════════════════════════════════════

  @Input() ariaLabel?: string;
  @Input() ariaDescribedby?: string;
  @Input() testId?: string;

  // ══════════════════════════════════════════════════════════════════════════
  // INPUTS - DEVELOPER EXPERIENCE
  // ══════════════════════════════════════════════════════════════════════════

  @Input() showQualityWarnings = true;

  // ══════════════════════════════════════════════════════════════════════════
  // OUTPUTS
  // ══════════════════════════════════════════════════════════════════════════

  @Output() checkedChange = new EventEmitter<boolean>();
  @Output() checkboxFocus = new EventEmitter<FocusEvent>();
  @Output() checkboxBlur = new EventEmitter<FocusEvent>();

  // ══════════════════════════════════════════════════════════════════════════
  // VIEW CHILD (for indeterminate state sync)
  // ══════════════════════════════════════════════════════════════════════════

  @ViewChild('inputRef', { static: false }) inputRef?: ElementRef<HTMLInputElement>;

  // ══════════════════════════════════════════════════════════════════════════
  // STATE (Angular-specific)
  // ══════════════════════════════════════════════════════════════════════════

  protected isHovered = false;
  protected isFocused = false;

  // ══════════════════════════════════════════════════════════════════════════
  // CHECKBOX CORE OUTPUT (computed)
  // ══════════════════════════════════════════════════════════════════════════

  protected currentState!: CheckboxState;
  protected resolvedTokens!: ResolvedCheckboxTokens;
  protected checkboxStyles!: CheckboxStyles;
  protected ariaAttrs!: ARIAAttributes;
  protected classNames!: string;
  protected sizeConfig!: SizeConfig;
  protected qualityWarnings: QualityWarning[] = [];

  // Class prefix for template
  protected readonly CLASS_PREFIX = CLASS_PREFIX;

  // ══════════════════════════════════════════════════════════════════════════
  // COMPUTED PROPERTIES
  // ══════════════════════════════════════════════════════════════════════════

  protected get showIcon(): boolean {
    return this.checked || this.indeterminate;
  }

  // ══════════════════════════════════════════════════════════════════════════
  // LIFECYCLE
  // ══════════════════════════════════════════════════════════════════════════

  ngOnChanges(changes: SimpleChanges): void {
    // Recompute checkbox output when inputs change
    this.updateCheckboxOutput();

    // Sync indeterminate state with native checkbox
    if (changes['indeterminate'] && this.inputRef) {
      this.inputRef.nativeElement.indeterminate = this.indeterminate;
    }
  }

  ngAfterViewInit(): void {
    // Initial sync of indeterminate state
    if (this.inputRef) {
      this.inputRef.nativeElement.indeterminate = this.indeterminate;
    }
  }

  // ══════════════════════════════════════════════════════════════════════════
  // CHECKBOX CORE INTEGRATION
  // ══════════════════════════════════════════════════════════════════════════

  /**
   * Update checkbox output via CheckboxCore.
   *
   * This method delegates ALL logic to CheckboxCore.processCheckbox().
   * NO logic duplication - pure delegation.
   */
  private updateCheckboxOutput(): void {
    const output = CheckboxCore.processCheckbox({
      // Tokens
      tokens: {
        backgroundColor: this.backgroundColor,
        borderColor: this.borderColor,
        checkColor: this.checkColor,
        labelColor: this.labelColor,
        hoverBackgroundColor: this.hoverBackgroundColor,
        hoverBorderColor: this.hoverBorderColor,
        focusBackgroundColor: this.focusBackgroundColor,
        focusBorderColor: this.focusBorderColor,
        focusOutlineColor: this.focusOutlineColor,
        checkedBackgroundColor: this.checkedBackgroundColor,
        checkedBorderColor: this.checkedBorderColor,
        checkedCheckColor: this.checkedCheckColor,
        checkedHoverBackgroundColor: this.checkedHoverBackgroundColor,
        checkedHoverBorderColor: this.checkedHoverBorderColor,
        checkedHoverCheckColor: this.checkedHoverCheckColor,
        checkedFocusBackgroundColor: this.checkedFocusBackgroundColor,
        checkedFocusBorderColor: this.checkedFocusBorderColor,
        checkedFocusCheckColor: this.checkedFocusCheckColor,
        checkedFocusOutlineColor: this.checkedFocusOutlineColor,
        indeterminateBackgroundColor: this.indeterminateBackgroundColor,
        indeterminateBorderColor: this.indeterminateBorderColor,
        indeterminateCheckColor: this.indeterminateCheckColor,
        indeterminateHoverBackgroundColor: this.indeterminateHoverBackgroundColor,
        indeterminateHoverBorderColor: this.indeterminateHoverBorderColor,
        indeterminateHoverCheckColor: this.indeterminateHoverCheckColor,
        indeterminateFocusBackgroundColor: this.indeterminateFocusBackgroundColor,
        indeterminateFocusBorderColor: this.indeterminateFocusBorderColor,
        indeterminateFocusCheckColor: this.indeterminateFocusCheckColor,
        indeterminateFocusOutlineColor: this.indeterminateFocusOutlineColor,
        disabledBackgroundColor: this.disabledBackgroundColor,
        disabledBorderColor: this.disabledBorderColor,
        disabledCheckColor: this.disabledCheckColor,
        disabledLabelColor: this.disabledLabelColor,
        checkedDisabledBackgroundColor: this.checkedDisabledBackgroundColor,
        checkedDisabledBorderColor: this.checkedDisabledBorderColor,
        checkedDisabledCheckColor: this.checkedDisabledCheckColor,
        indeterminateDisabledBackgroundColor: this.indeterminateDisabledBackgroundColor,
        indeterminateDisabledBorderColor: this.indeterminateDisabledBorderColor,
        indeterminateDisabledCheckColor: this.indeterminateDisabledCheckColor,
      },

      // Check state
      isChecked: this.checked,
      isIndeterminate: this.indeterminate,

      // Interaction state
      disabled: this.disabled,
      isHovered: this.isHovered,
      isFocused: this.isFocused,

      // Layout
      size: this.size,

      // Content
      label: this.label,

      // ARIA
      required: this.required,
      invalid: this.invalid,
      ariaLabel: this.ariaLabel,
      ariaDescribedby: this.ariaDescribedby,

      // Styles
      userStyles: this.customStyle,

      // Dev mode
      showQualityWarnings: this.showQualityWarnings,
      customClass: this.customClass,
    });

    // Update component properties
    this.currentState = output.currentState;
    this.resolvedTokens = output.resolvedTokens;
    this.checkboxStyles = output.styles;
    this.ariaAttrs = output.ariaAttrs;
    this.classNames = output.classNames;
    this.sizeConfig = output.sizeConfig;
    this.qualityWarnings = output.qualityWarnings;

    // Log quality warnings
    if (this.qualityWarnings.length > 0) {
      this.qualityWarnings.forEach((warning) => {
        console.warn(`[Checkbox] ${warning.message}`, warning.details);
      });
    }
  }

  // ══════════════════════════════════════════════════════════════════════════
  // EVENT HANDLERS (Angular-specific)
  // ══════════════════════════════════════════════════════════════════════════

  protected onChange(event: Event): void {
    if (this.disabled) {
      return;
    }
    const target = event.target as HTMLInputElement;
    this.checked = target.checked;
    this.checkedChange.emit(this.checked);
  }

  protected onMouseEnter(): void {
    if (this.disabled) {
      return;
    }
    this.isHovered = true;
    this.updateCheckboxOutput();
  }

  protected onMouseLeave(): void {
    this.isHovered = false;
    this.updateCheckboxOutput();
  }

  protected onFocus(event: FocusEvent): void {
    if (this.disabled) {
      return;
    }
    this.isFocused = true;
    this.updateCheckboxOutput();
    this.checkboxFocus.emit(event);
  }

  protected onBlur(event: FocusEvent): void {
    this.isFocused = false;
    this.updateCheckboxOutput();
    this.checkboxBlur.emit(event);
  }

  // ══════════════════════════════════════════════════════════════════════════
  // TEMPLATE UTILITIES
  // ══════════════════════════════════════════════════════════════════════════

  /**
   * Get container style object for [ngStyle].
   */
  protected getContainerStyle(): Record<string, string | number> {
    return {
      'display': this.checkboxStyles.containerDisplay || 'inline-flex',
      'align-items': this.checkboxStyles.containerAlignItems || 'center',
      'gap': `${this.checkboxStyles.containerGap}px`,
      'cursor': this.checkboxStyles.containerCursor || 'pointer',
      'opacity': this.checkboxStyles.containerOpacity ?? 1,
    };
  }

  /**
   * Get box style object for [ngStyle].
   */
  protected getBoxStyle(): Record<string, string | number> {
    const styles: Record<string, string | number> = {
      'position': 'relative',
      'width': `${this.checkboxStyles.boxWidth}px`,
      'height': `${this.checkboxStyles.boxHeight}px`,
      'background-color': this.checkboxStyles.boxBackgroundColor,
      'border-width': `${this.checkboxStyles.boxBorderWidth}px`,
      'border-style': this.checkboxStyles.boxBorderStyle,
      'border-color': this.checkboxStyles.boxBorderColor,
      'border-radius': `${this.checkboxStyles.boxBorderRadius}px`,
      'display': this.checkboxStyles.boxDisplay || 'inline-flex',
      'align-items': this.checkboxStyles.boxAlignItems || 'center',
      'justify-content': this.checkboxStyles.boxJustifyContent || 'center',
      'transition': this.checkboxStyles.boxTransition || 'none',
    };

    if (this.checkboxStyles.outlineColor) {
      styles['outline'] = `${this.checkboxStyles.outlineWidth}px solid ${this.checkboxStyles.outlineColor}`;
      styles['outline-offset'] = `${this.checkboxStyles.outlineOffset}px`;
    }

    return styles;
  }

  /**
   * Get icon style object for [ngStyle].
   */
  protected getIconStyle(): Record<string, string | number> {
    return {
      'width': `${this.checkboxStyles.iconSize}px`,
      'height': `${this.checkboxStyles.iconSize}px`,
      'color': this.checkboxStyles.iconColor,
      'display': this.checkboxStyles.iconDisplay || 'block',
    };
  }

  /**
   * Get label style object for [ngStyle].
   */
  protected getLabelStyle(): Record<string, string | number> | null {
    if (!this.checkboxStyles.labelColor) {
      return null;
    }

    return {
      'font-size': `${this.checkboxStyles.labelFontSize}px`,
      'color': this.checkboxStyles.labelColor,
    };
  }
}

/**
 * CONTRACT COMPLIANCE:
 *
 * ✅ Zero logic duplication
 *    - ALL logic delegated to CheckboxCore.processCheckbox()
 *    - Component is wrapper around CheckboxCore
 *    - Adapter is THIN
 *
 * ✅ 100% token-driven
 *    - All colors from EnrichedToken (via CheckboxCore)
 *    - NO local color calculations
 *
 * ✅ State management via framework
 *    - Uses Angular component properties for interaction state
 *    - CheckboxCore handles state determination
 *
 * ✅ Framework-specific concerns only
 *    - Template rendering (Angular-specific)
 *    - Event handling (Angular events → CheckboxCore)
 *    - Change detection (Angular OnChanges)
 *    - Indeterminate sync (Angular AfterViewInit + ViewChild)
 *
 * ✅ Identical behavior to React/Vue/Svelte
 *    - Same CheckboxCore
 *    - Same tokens
 *    - Same output
 *
 * ✅ Tri-state support
 *    - Unchecked, checked, indeterminate
 *    - Proper ARIA compliance
 *
 * PATTERN: Exact copy of textfield.component.ts adapted for Checkbox
 */

// src/adapters/svelte/checkbox/Checkbox.svelte
<script lang="ts">
/**
 * @fileoverview Svelte Checkbox Adapter
 *
 * FASE 15: Component Expansion
 *
 * Svelte adapter for CheckboxCore.
 * This is a THIN wrapper that delegates all logic to CheckboxCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to CheckboxCore)
 * - ✅ 100% token-driven (via CheckboxCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/svelte/checkbox
 * @version 1.0.0
 */

import { onMount } from 'svelte';
import { CheckboxCore, CLASS_PREFIX } from '../../core/checkbox';
import type { CheckboxProps } from './types';

// ============================================================================
// PROPS
// ============================================================================

// Check state
export let checked: CheckboxProps['checked'] = false;
export let indeterminate: CheckboxProps['indeterminate'] = false;
export let label: CheckboxProps['label'] = undefined;

// Tokens - Base
export let backgroundColor: CheckboxProps['backgroundColor'];
export let borderColor: CheckboxProps['borderColor'];
export let checkColor: CheckboxProps['checkColor'];
export let labelColor: CheckboxProps['labelColor'] = undefined;

// Tokens - Hover
export let hoverBackgroundColor: CheckboxProps['hoverBackgroundColor'] = undefined;
export let hoverBorderColor: CheckboxProps['hoverBorderColor'] = undefined;

// Tokens - Focus
export let focusBackgroundColor: CheckboxProps['focusBackgroundColor'] = undefined;
export let focusBorderColor: CheckboxProps['focusBorderColor'] = undefined;
export let focusOutlineColor: CheckboxProps['focusOutlineColor'] = undefined;

// Tokens - Checked
export let checkedBackgroundColor: CheckboxProps['checkedBackgroundColor'] = undefined;
export let checkedBorderColor: CheckboxProps['checkedBorderColor'] = undefined;
export let checkedCheckColor: CheckboxProps['checkedCheckColor'] = undefined;

export let checkedHoverBackgroundColor: CheckboxProps['checkedHoverBackgroundColor'] = undefined;
export let checkedHoverBorderColor: CheckboxProps['checkedHoverBorderColor'] = undefined;
export let checkedHoverCheckColor: CheckboxProps['checkedHoverCheckColor'] = undefined;

export let checkedFocusBackgroundColor: CheckboxProps['checkedFocusBackgroundColor'] = undefined;
export let checkedFocusBorderColor: CheckboxProps['checkedFocusBorderColor'] = undefined;
export let checkedFocusCheckColor: CheckboxProps['checkedFocusCheckColor'] = undefined;
export let checkedFocusOutlineColor: CheckboxProps['checkedFocusOutlineColor'] = undefined;

// Tokens - Indeterminate
export let indeterminateBackgroundColor: CheckboxProps['indeterminateBackgroundColor'] = undefined;
export let indeterminateBorderColor: CheckboxProps['indeterminateBorderColor'] = undefined;
export let indeterminateCheckColor: CheckboxProps['indeterminateCheckColor'] = undefined;

export let indeterminateHoverBackgroundColor: CheckboxProps['indeterminateHoverBackgroundColor'] = undefined;
export let indeterminateHoverBorderColor: CheckboxProps['indeterminateHoverBorderColor'] = undefined;
export let indeterminateHoverCheckColor: CheckboxProps['indeterminateHoverCheckColor'] = undefined;

export let indeterminateFocusBackgroundColor: CheckboxProps['indeterminateFocusBackgroundColor'] = undefined;
export let indeterminateFocusBorderColor: CheckboxProps['indeterminateFocusBorderColor'] = undefined;
export let indeterminateFocusCheckColor: CheckboxProps['indeterminateFocusCheckColor'] = undefined;
export let indeterminateFocusOutlineColor: CheckboxProps['indeterminateFocusOutlineColor'] = undefined;

// Tokens - Disabled
export let disabledBackgroundColor: CheckboxProps['disabledBackgroundColor'] = undefined;
export let disabledBorderColor: CheckboxProps['disabledBorderColor'] = undefined;
export let disabledCheckColor: CheckboxProps['disabledCheckColor'] = undefined;
export let disabledLabelColor: CheckboxProps['disabledLabelColor'] = undefined;

export let checkedDisabledBackgroundColor: CheckboxProps['checkedDisabledBackgroundColor'] = undefined;
export let checkedDisabledBorderColor: CheckboxProps['checkedDisabledBorderColor'] = undefined;
export let checkedDisabledCheckColor: CheckboxProps['checkedDisabledCheckColor'] = undefined;

export let indeterminateDisabledBackgroundColor: CheckboxProps['indeterminateDisabledBackgroundColor'] = undefined;
export let indeterminateDisabledBorderColor: CheckboxProps['indeterminateDisabledBorderColor'] = undefined;
export let indeterminateDisabledCheckColor: CheckboxProps['indeterminateDisabledCheckColor'] = undefined;

// Behavior
export let disabled: CheckboxProps['disabled'] = false;
export let required: CheckboxProps['required'] = false;
export let invalid: CheckboxProps['invalid'] = false;

// Layout
export let size: CheckboxProps['size'] = 'md';

// Styling
let className: CheckboxProps['class'] = undefined;
export { className as class };
export let style: CheckboxProps['style'] = undefined;

// Accessibility
export let ariaLabel: CheckboxProps['ariaLabel'] = undefined;
export let ariaDescribedby: CheckboxProps['ariaDescribedby'] = undefined;
export let testId: CheckboxProps['testId'] = undefined;

// Developer experience
export let showQualityWarnings: CheckboxProps['showQualityWarnings'] = true;

// ============================================================================
// STATE (Svelte-specific)
// ============================================================================

let isHovered = false;
let isFocused = false;
let inputRef: HTMLInputElement | null = null;

// ============================================================================
// INDETERMINATE STATE SYNC
// ============================================================================

// Sync indeterminate state with native checkbox property
$: if (inputRef) {
  inputRef.indeterminate = indeterminate;
}

onMount(() => {
  if (inputRef) {
    inputRef.indeterminate = indeterminate;
  }
});

// ============================================================================
// CHECKBOX CORE INTEGRATION
// ============================================================================

/**
 * Process checkbox logic via CheckboxCore.
 *
 * This reactive statement delegates ALL logic to CheckboxCore.processCheckbox().
 * NO logic duplication - pure delegation.
 */
$: checkboxOutput = CheckboxCore.processCheckbox({
  // Tokens
  tokens: {
    backgroundColor,
    borderColor,
    checkColor,
    labelColor,
    hoverBackgroundColor,
    hoverBorderColor,
    focusBackgroundColor,
    focusBorderColor,
    focusOutlineColor,
    checkedBackgroundColor,
    checkedBorderColor,
    checkedCheckColor,
    checkedHoverBackgroundColor,
    checkedHoverBorderColor,
    checkedHoverCheckColor,
    checkedFocusBackgroundColor,
    checkedFocusBorderColor,
    checkedFocusCheckColor,
    checkedFocusOutlineColor,
    indeterminateBackgroundColor,
    indeterminateBorderColor,
    indeterminateCheckColor,
    indeterminateHoverBackgroundColor,
    indeterminateHoverBorderColor,
    indeterminateHoverCheckColor,
    indeterminateFocusBackgroundColor,
    indeterminateFocusBorderColor,
    indeterminateFocusCheckColor,
    indeterminateFocusOutlineColor,
    disabledBackgroundColor,
    disabledBorderColor,
    disabledCheckColor,
    disabledLabelColor,
    checkedDisabledBackgroundColor,
    checkedDisabledBorderColor,
    checkedDisabledCheckColor,
    indeterminateDisabledBackgroundColor,
    indeterminateDisabledBorderColor,
    indeterminateDisabledCheckColor,
  },

  // Check state
  isChecked: checked,
  isIndeterminate: indeterminate,

  // Interaction state
  disabled,
  isHovered,
  isFocused,

  // Layout
  size,

  // Content
  label,

  // ARIA
  required,
  invalid,
  ariaLabel,
  ariaDescribedby,

  // Styles
  userStyles: style,

  // Dev mode
  showQualityWarnings,
  customClass: className,
});

// ============================================================================
// QUALITY WARNINGS (DEV MODE)
// ============================================================================

// Log quality warnings
$: if (checkboxOutput.qualityWarnings.length > 0) {
  checkboxOutput.qualityWarnings.forEach((warning) => {
    console.warn(`[Checkbox] ${warning.message}`, warning.details);
  });
}

// ============================================================================
// COMPUTED STYLES
// ============================================================================

$: containerStyles = [
  `display: ${checkboxOutput.styles.containerDisplay}`,
  `align-items: ${checkboxOutput.styles.containerAlignItems}`,
  `gap: ${checkboxOutput.styles.containerGap}px`,
  `cursor: ${checkboxOutput.styles.containerCursor}`,
  `opacity: ${checkboxOutput.styles.containerOpacity}`,
].join('; ');

$: boxStyles = [
  'position: relative',
  `width: ${checkboxOutput.styles.boxWidth}px`,
  `height: ${checkboxOutput.styles.boxHeight}px`,
  `background-color: ${checkboxOutput.styles.boxBackgroundColor}`,
  `border-width: ${checkboxOutput.styles.boxBorderWidth}px`,
  `border-style: ${checkboxOutput.styles.boxBorderStyle}`,
  `border-color: ${checkboxOutput.styles.boxBorderColor}`,
  `border-radius: ${checkboxOutput.styles.boxBorderRadius}px`,
  `display: ${checkboxOutput.styles.boxDisplay}`,
  `align-items: ${checkboxOutput.styles.boxAlignItems}`,
  `justify-content: ${checkboxOutput.styles.boxJustifyContent}`,
  `transition: ${checkboxOutput.styles.boxTransition}`,
  checkboxOutput.styles.outlineColor ? `outline: ${checkboxOutput.styles.outlineWidth}px solid ${checkboxOutput.styles.outlineColor}` : '',
  checkboxOutput.styles.outlineColor ? `outline-offset: ${checkboxOutput.styles.outlineOffset}px` : '',
].filter(Boolean).join('; ');

$: iconStyles = [
  `width: ${checkboxOutput.styles.iconSize}px`,
  `height: ${checkboxOutput.styles.iconSize}px`,
  `color: ${checkboxOutput.styles.iconColor}`,
  `display: ${checkboxOutput.styles.iconDisplay}`,
].join('; ');

$: labelStyles = checkboxOutput.styles.labelColor ? [
  `font-size: ${checkboxOutput.styles.labelFontSize}px`,
  `color: ${checkboxOutput.styles.labelColor}`,
].join('; ') : '';

$: showIcon = checked || indeterminate;

// ============================================================================
// EVENT HANDLERS (Svelte-specific)
// ============================================================================

import { createEventDispatcher } from 'svelte';

const dispatch = createEventDispatcher<{
  change: boolean;
  focus: FocusEvent;
  blur: FocusEvent;
}>();

function handleChange(event: Event) {
  if (disabled) {
    return;
  }
  const target = event.target as HTMLInputElement;
  checked = target.checked;
  dispatch('change', checked);
}

function handleMouseEnter() {
  if (disabled) {
    return;
  }
  isHovered = true;
}

function handleMouseLeave() {
  isHovered = false;
}

function handleFocus(event: FocusEvent) {
  if (disabled) {
    return;
  }
  isFocused = true;
  dispatch('focus', event);
}

function handleBlur(event: FocusEvent) {
  isFocused = false;
  dispatch('blur', event);
}
</script>

<label
  style={containerStyles}
  class={checkboxOutput.classNames}
  on:mouseenter={handleMouseEnter}
  on:mouseleave={handleMouseLeave}
>
  <!-- Hidden native checkbox (for accessibility and form submission) -->
  <input
    bind:this={inputRef}
    type="checkbox"
    {checked}
    on:change={handleChange}
    on:focus={handleFocus}
    on:blur={handleBlur}
    {disabled}
    {required}
    style="position: absolute; opacity: 0; width: 1px; height: 1px; margin: -1px;"
    aria-checked={checkboxOutput.ariaAttrs['aria-checked']}
    aria-disabled={checkboxOutput.ariaAttrs['aria-disabled']}
    aria-label={checkboxOutput.ariaAttrs['aria-label']}
    aria-describedby={checkboxOutput.ariaAttrs['aria-describedby']}
    aria-required={checkboxOutput.ariaAttrs['aria-required']}
    aria-invalid={checkboxOutput.ariaAttrs['aria-invalid']}
    data-momoto-bg-quality={showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.qualityScore : undefined}
    data-momoto-bg-decision={showQualityWarnings ? checkboxOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined}
    data-momoto-check-quality={showQualityWarnings ? checkboxOutput.resolvedTokens.checkColor.qualityScore : undefined}
    data-testid={testId}
  />

  <!-- Visual checkbox box -->
  <span
    class="{CLASS_PREFIX}__box"
    style={boxStyles}
  >
    <!-- Checkmark or dash icon -->
    {#if showIcon}
      <svg
        class="{CLASS_PREFIX}__icon"
        style={iconStyles}
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
      >
        {#if indeterminate}
          <!-- Dash icon for indeterminate state -->
          <path
            d="M4 8h8"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
          />
        {:else}
          <!-- Checkmark icon for checked state -->
          <path
            d="M3 8l3 3 7-7"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        {/if}
      </svg>
    {/if}
  </span>

  <!-- Label (optional) -->
  {#if label}
    <span
      class="{CLASS_PREFIX}__label"
      style={labelStyles}
    >
      {label}
    </span>
  {/if}
</label>

<!--
CONTRACT COMPLIANCE:

✅ Zero logic duplication
   - ALL logic delegated to CheckboxCore.processCheckbox()
   - Adapter is THIN wrapper

✅ 100% token-driven
   - All colors from EnrichedToken (via CheckboxCore)
   - NO local color calculations

✅ State management via framework
   - Uses Svelte's reactive let for interaction state
   - CheckboxCore handles state determination

✅ Framework-specific concerns only
   - Template rendering (Svelte-specific)
   - Event handling (Svelte events → CheckboxCore)
   - Reactivity (Svelte $: reactive statements)
   - Indeterminate state sync (Svelte $: + onMount)

✅ Identical behavior to React/Vue
   - Same CheckboxCore
   - Same tokens
   - Same output

✅ Tri-state support
   - Unchecked, checked, indeterminate
   - Proper ARIA compliance

PATTERN: Exact copy of TextField.svelte adapted for Checkbox
-->
