// adapters/svelte/textfield/TextField.svelte
<script lang="ts">
/**
 * @fileoverview Svelte TextField Adapter
 *
 * FASE 15: Component Expansion
 *
 * Svelte adapter for TextFieldCore.
 * This is a THIN wrapper that delegates all logic to TextFieldCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to TextFieldCore)
 * - ✅ 100% token-driven (via TextFieldCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/svelte/textfield
 * @version 1.0.0
 */

import { createEventDispatcher } from 'svelte';
import { TextFieldCore, CLASS_PREFIX } from '../../core/textfield';
import type { TextFieldProps } from './types';

// ============================================================================
// PROPS
// ============================================================================

// Content
export let value: TextFieldProps['value'];
export let placeholder: TextFieldProps['placeholder'] = undefined;
export let label: TextFieldProps['label'] = undefined;
export let helperText: TextFieldProps['helperText'] = undefined;

// Tokens - Base
export let backgroundColor: TextFieldProps['backgroundColor'];
export let textColor: TextFieldProps['textColor'];
export let borderColor: TextFieldProps['borderColor'] = undefined;
export let placeholderColor: TextFieldProps['placeholderColor'] = undefined;
export let labelColor: TextFieldProps['labelColor'] = undefined;
export let helperTextColor: TextFieldProps['helperTextColor'] = undefined;

// Tokens - Hover
export let hoverBackgroundColor: TextFieldProps['hoverBackgroundColor'] = undefined;
export let hoverBorderColor: TextFieldProps['hoverBorderColor'] = undefined;

// Tokens - Focus
export let focusBackgroundColor: TextFieldProps['focusBackgroundColor'] = undefined;
export let focusBorderColor: TextFieldProps['focusBorderColor'] = undefined;

// Tokens - Error
export let errorBackgroundColor: TextFieldProps['errorBackgroundColor'] = undefined;
export let errorTextColor: TextFieldProps['errorTextColor'] = undefined;
export let errorBorderColor: TextFieldProps['errorBorderColor'] = undefined;
export let errorLabelColor: TextFieldProps['errorLabelColor'] = undefined;
export let errorHelperTextColor: TextFieldProps['errorHelperTextColor'] = undefined;

// Tokens - Success
export let successBackgroundColor: TextFieldProps['successBackgroundColor'] = undefined;
export let successTextColor: TextFieldProps['successTextColor'] = undefined;
export let successBorderColor: TextFieldProps['successBorderColor'] = undefined;
export let successLabelColor: TextFieldProps['successLabelColor'] = undefined;
export let successHelperTextColor: TextFieldProps['successHelperTextColor'] = undefined;

// Tokens - Disabled
export let disabledBackgroundColor: TextFieldProps['disabledBackgroundColor'] = undefined;
export let disabledTextColor: TextFieldProps['disabledTextColor'] = undefined;
export let disabledBorderColor: TextFieldProps['disabledBorderColor'] = undefined;
export let disabledLabelColor: TextFieldProps['disabledLabelColor'] = undefined;

// Behavior
export let type: TextFieldProps['type'] = 'text';
export let disabled: TextFieldProps['disabled'] = false;
export let error: TextFieldProps['error'] = false;
export let success: TextFieldProps['success'] = false;
export let required: TextFieldProps['required'] = false;

// Layout
export let size: TextFieldProps['size'] = 'md';
export let fullWidth: TextFieldProps['fullWidth'] = false;
export let multiline: TextFieldProps['multiline'] = false;
export let rows: TextFieldProps['rows'] = 3;

// Styling
let className: TextFieldProps['class'] = undefined;
export { className as class };
export let style: TextFieldProps['style'] = undefined;

// Accessibility
export let ariaLabel: TextFieldProps['ariaLabel'] = undefined;
export let ariaDescribedby: TextFieldProps['ariaDescribedby'] = undefined;
export let testId: TextFieldProps['testId'] = undefined;

// Developer experience
export let showQualityWarnings: TextFieldProps['showQualityWarnings'] = true;

// ============================================================================
// STATE (Svelte-specific)
// ============================================================================

let isHovered = false;
let isFocused = false;

// ============================================================================
// TEXTFIELD CORE INTEGRATION
// ============================================================================

/**
 * Process text field logic via TextFieldCore.
 *
 * This reactive statement delegates ALL logic to TextFieldCore.processTextField().
 * NO logic duplication - pure delegation.
 */
$: textFieldOutput = TextFieldCore.processTextField({
  // Tokens
  tokens: {
    backgroundColor,
    textColor,
    borderColor,
    placeholderColor,
    labelColor,
    helperTextColor,
    hoverBackgroundColor,
    hoverBorderColor,
    focusBackgroundColor,
    focusBorderColor,
    errorBackgroundColor,
    errorTextColor,
    errorBorderColor,
    errorLabelColor,
    errorHelperTextColor,
    successBackgroundColor,
    successTextColor,
    successBorderColor,
    successLabelColor,
    successHelperTextColor,
    disabledBackgroundColor,
    disabledTextColor,
    disabledBorderColor,
    disabledLabelColor,
  },

  // Interaction state
  disabled,
  error,
  success,
  isHovered,
  isFocused,

  // Layout
  size,
  fullWidth,
  multiline,

  // Content
  label,
  helperText,

  // ARIA
  required,
  ariaLabel,
  ariaDescribedby,

  // Styles
  userStyles: style,

  // Dev mode
  showQualityWarnings,
  customClass: className,
});

// ============================================================================
// QUALITY WARNINGS (DEV MODE)
// ============================================================================

// Log quality warnings
$: if (textFieldOutput.qualityWarnings.length > 0) {
  textFieldOutput.qualityWarnings.forEach((warning) => {
    console.warn(`[TextField] ${warning.message}`, warning.details);
  });
}

// ============================================================================
// COMPUTED STYLES
// ============================================================================

$: containerStyles = [
  `width: ${textFieldOutput.styles.containerWidth}`,
  `display: ${textFieldOutput.styles.containerDisplay}`,
  `flex-direction: ${textFieldOutput.styles.containerFlexDirection}`,
  `gap: ${textFieldOutput.styles.containerGap}px`,
].join('; ');

$: inputStyles = [
  multiline ? 'height: auto' : `height: ${textFieldOutput.styles.inputHeight}px`,
  `padding-left: ${textFieldOutput.styles.inputPaddingLeft}px`,
  `padding-right: ${textFieldOutput.styles.inputPaddingRight}px`,
  `padding-top: ${textFieldOutput.styles.inputPaddingTop}px`,
  `padding-bottom: ${textFieldOutput.styles.inputPaddingBottom}px`,
  `font-size: ${textFieldOutput.styles.inputFontSize}px`,
  `font-weight: ${textFieldOutput.styles.inputFontWeight}`,
  `line-height: ${textFieldOutput.styles.inputLineHeight}`,
  `font-family: ${textFieldOutput.styles.inputFontFamily}`,
  `background-color: ${textFieldOutput.styles.inputBackgroundColor}`,
  `color: ${textFieldOutput.styles.inputColor}`,
  `border-radius: ${textFieldOutput.styles.inputBorderRadius}px`,
  `outline: ${textFieldOutput.styles.inputOutline}`,
  `cursor: ${textFieldOutput.styles.inputCursor}`,
  `transition: ${textFieldOutput.styles.inputTransition}`,
  textFieldOutput.styles.inputBorderWidth ? `border-width: ${textFieldOutput.styles.inputBorderWidth}px` : '',
  textFieldOutput.styles.inputBorderStyle ? `border-style: ${textFieldOutput.styles.inputBorderStyle}` : '',
  textFieldOutput.styles.inputBorderColor ? `border-color: ${textFieldOutput.styles.inputBorderColor}` : '',
].filter(Boolean).join('; ');

$: labelStyles = textFieldOutput.styles.labelColor ? [
  `font-size: ${textFieldOutput.styles.labelFontSize}px`,
  `font-weight: ${textFieldOutput.styles.labelFontWeight}`,
  `color: ${textFieldOutput.styles.labelColor}`,
  `margin-bottom: ${textFieldOutput.styles.labelMarginBottom}px`,
].join('; ') : '';

$: helperStyles = textFieldOutput.styles.helperColor ? [
  `font-size: ${textFieldOutput.styles.helperFontSize}px`,
  `color: ${textFieldOutput.styles.helperColor}`,
  `margin-top: ${textFieldOutput.styles.helperMarginTop}px`,
].join('; ') : '';

// ============================================================================
// EVENT HANDLERS (Svelte-specific)
// ============================================================================

const dispatch = createEventDispatcher<{
  input: string;
  focus: FocusEvent;
  blur: FocusEvent;
}>();

function handleInput(event: Event) {
  if (disabled) {
    return;
  }
  const target = event.target as HTMLInputElement | HTMLTextAreaElement;
  value = target.value;
  dispatch('input', value);
}

function handleMouseEnter() {
  if (disabled) {
    return;
  }
  isHovered = true;
}

function handleMouseLeave() {
  isHovered = false;
}

function handleFocus(event: FocusEvent) {
  if (disabled) {
    return;
  }
  isFocused = true;
  dispatch('focus', event);
}

function handleBlur(event: FocusEvent) {
  isFocused = false;
  dispatch('blur', event);
}
</script>

<div style={containerStyles} class={textFieldOutput.classNames}>
  <!-- Label (optional) -->
  {#if label}
    <label
      class="{CLASS_PREFIX}__label"
      style={labelStyles}
    >
      {label}
      {#if required}<span aria-label="required"> *</span>{/if}
    </label>
  {/if}

  <!-- Input (single-line) -->
  {#if !multiline}
    <input
      {type}
      {value}
      {placeholder}
      {disabled}
      {required}
      class="{CLASS_PREFIX}__input"
      style={inputStyles}
      aria-label={textFieldOutput.ariaAttrs['aria-label']}
      aria-describedby={textFieldOutput.ariaAttrs['aria-describedby']}
      aria-disabled={textFieldOutput.ariaAttrs['aria-disabled']}
      aria-invalid={textFieldOutput.ariaAttrs['aria-invalid']}
      aria-required={textFieldOutput.ariaAttrs['aria-required']}
      data-momoto-bg-quality={showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.qualityScore : undefined}
      data-momoto-bg-decision={showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined}
      data-momoto-text-quality={showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.qualityScore : undefined}
      data-momoto-wcag-ratio={showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.accessibility?.wcagRatio : undefined}
      data-testid={testId}
      on:input={handleInput}
      on:focus={handleFocus}
      on:blur={handleBlur}
      on:mouseenter={handleMouseEnter}
      on:mouseleave={handleMouseLeave}
    />
  {:else}
    <!-- Textarea (multiline) -->
    <textarea
      {value}
      {placeholder}
      {disabled}
      {required}
      {rows}
      class="{CLASS_PREFIX}__input {CLASS_PREFIX}__input--multiline"
      style={inputStyles}
      aria-label={textFieldOutput.ariaAttrs['aria-label']}
      aria-describedby={textFieldOutput.ariaAttrs['aria-describedby']}
      aria-disabled={textFieldOutput.ariaAttrs['aria-disabled']}
      aria-invalid={textFieldOutput.ariaAttrs['aria-invalid']}
      aria-required={textFieldOutput.ariaAttrs['aria-required']}
      data-momoto-bg-quality={showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.qualityScore : undefined}
      data-momoto-bg-decision={showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined}
      data-momoto-text-quality={showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.qualityScore : undefined}
      data-momoto-wcag-ratio={showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.accessibility?.wcagRatio : undefined}
      data-testid={testId}
      on:input={handleInput}
      on:focus={handleFocus}
      on:blur={handleBlur}
      on:mouseenter={handleMouseEnter}
      on:mouseleave={handleMouseLeave}
    />
  {/if}

  <!-- Helper text (optional) -->
  {#if helperText}
    <div
      class="{CLASS_PREFIX}__helper"
      style={helperStyles}
    >
      {helperText}
    </div>
  {/if}
</div>

<!--
CONTRACT COMPLIANCE:

✅ Zero logic duplication
   - ALL logic delegated to TextFieldCore.processTextField()
   - Adapter is THIN wrapper

✅ 100% token-driven
   - All colors from EnrichedToken (via TextFieldCore)
   - NO local color calculations

✅ State management via framework
   - Uses Svelte's reactive let for interaction state
   - TextFieldCore handles state determination

✅ Framework-specific concerns only
   - Template rendering (Svelte-specific)
   - Event handling (Svelte events → TextFieldCore)
   - Reactivity (Svelte $: reactive statements)

✅ Identical behavior to React/Vue
   - Same TextFieldCore
   - Same tokens
   - Same output

PATTERN: Exact copy of Button.svelte adapted for TextField

USAGE EXAMPLE:

```svelte
<script>
  import { TextField } from '@momoto/ui-adapters/svelte/textfield';

  let email = '';
  let inputBg = inputBackgroundToken;
  let inputText = inputTextToken;

  function handleInput(event) {
    console.log('Value:', event.detail);
  }
</script>

<TextField
  label="Email"
  bind:value={email}
  backgroundColor={inputBg}
  textColor={inputText}
  placeholder="Enter your email"
  type="email"
  on:input={handleInput}
/>
```
-->

// adapters/vue/textfield/TextField.vue
<template>
  <div :style="containerStyles" :class="textFieldOutput.classNames">
    <!-- Label (optional) -->
    <label
      v-if="label"
      :class="`${CLASS_PREFIX}__label`"
      :style="labelStyles"
    >
      {{ label }}
      <span v-if="required" aria-label="required"> *</span>
    </label>

    <!-- Input (single-line) -->
    <input
      v-if="!multiline"
      :type="type"
      :value="value"
      :placeholder="placeholder"
      :disabled="disabled"
      :required="required"
      :class="`${CLASS_PREFIX}__input`"
      :style="inputStyles"
      :aria-label="textFieldOutput.ariaAttrs['aria-label']"
      :aria-describedby="textFieldOutput.ariaAttrs['aria-describedby']"
      :aria-disabled="textFieldOutput.ariaAttrs['aria-disabled']"
      :aria-invalid="textFieldOutput.ariaAttrs['aria-invalid']"
      :aria-required="textFieldOutput.ariaAttrs['aria-required']"
      :data-momoto-bg-quality="showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.qualityScore : undefined"
      :data-momoto-bg-decision="showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined"
      :data-momoto-text-quality="showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.qualityScore : undefined"
      :data-momoto-wcag-ratio="showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.accessibility?.wcagRatio : undefined"
      :data-testid="testId"
      @input="handleInput"
      @focus="handleFocus"
      @blur="handleBlur"
      @mouseenter="handleMouseEnter"
      @mouseleave="handleMouseLeave"
    >

    <!-- Textarea (multiline) -->
    <textarea
      v-else
      :value="value"
      :placeholder="placeholder"
      :disabled="disabled"
      :required="required"
      :rows="rows"
      :class="`${CLASS_PREFIX}__input ${CLASS_PREFIX}__input--multiline`"
      :style="inputStyles"
      :aria-label="textFieldOutput.ariaAttrs['aria-label']"
      :aria-describedby="textFieldOutput.ariaAttrs['aria-describedby']"
      :aria-disabled="textFieldOutput.ariaAttrs['aria-disabled']"
      :aria-invalid="textFieldOutput.ariaAttrs['aria-invalid']"
      :aria-required="textFieldOutput.ariaAttrs['aria-required']"
      :data-momoto-bg-quality="showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.qualityScore : undefined"
      :data-momoto-bg-decision="showQualityWarnings ? textFieldOutput.resolvedTokens.backgroundColor.sourceDecisionId : undefined"
      :data-momoto-text-quality="showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.qualityScore : undefined"
      :data-momoto-wcag-ratio="showQualityWarnings ? textFieldOutput.resolvedTokens.textColor.accessibility?.wcagRatio : undefined"
      :data-testid="testId"
      @input="handleInput"
      @focus="handleFocus"
      @blur="handleBlur"
      @mouseenter="handleMouseEnter"
      @mouseleave="handleMouseLeave"
    />

    <!-- Helper text (optional) -->
    <div
      v-if="helperText"
      :class="`${CLASS_PREFIX}__helper`"
      :style="helperStyles"
    >
      {{ helperText }}
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * @fileoverview Vue TextField Adapter
 *
 * FASE 15: Component Expansion
 *
 * Vue 3 adapter for TextFieldCore.
 * This is a THIN wrapper that delegates all logic to TextFieldCore.
 *
 * CONTRACT COMPLIANCE:
 * - ✅ Zero logic duplication (delegates to TextFieldCore)
 * - ✅ 100% token-driven (via TextFieldCore)
 * - ✅ NO perceptual logic
 * - ✅ Framework-specific state management only
 *
 * @module momoto-ui/adapters/vue/textfield
 * @version 1.0.0
 */

import { ref, computed, watch } from 'vue';
import { TextFieldCore, CLASS_PREFIX } from '../../core/textfield';
import type { TextFieldProps } from './types';

// ============================================================================
// PROPS
// ============================================================================

const props = withDefaults(defineProps<TextFieldProps>(), {
  // Behavior
  disabled: false,
  error: false,
  success: false,
  required: false,
  type: 'text',

  // Layout
  size: 'md',
  fullWidth: false,
  multiline: false,
  rows: 3,

  // Dev mode
  showQualityWarnings: import.meta.env.DEV,
});

// ============================================================================
// EMITS
// ============================================================================

const emit = defineEmits<{
  'update:value': [value: string];
  focus: [event: FocusEvent];
  blur: [event: FocusEvent];
}>();

// ============================================================================
// STATE (Vue-specific)
// ============================================================================

const isHovered = ref(false);
const isFocused = ref(false);

// ============================================================================
// TEXTFIELD CORE INTEGRATION
// ============================================================================

/**
 * Process text field logic via TextFieldCore.
 *
 * This computed property delegates ALL logic to TextFieldCore.processTextField().
 * NO logic duplication - pure delegation.
 */
const textFieldOutput = computed(() => {
  return TextFieldCore.processTextField({
    // Tokens
    tokens: {
      backgroundColor: props.backgroundColor,
      textColor: props.textColor,
      borderColor: props.borderColor,
      placeholderColor: props.placeholderColor,
      labelColor: props.labelColor,
      helperTextColor: props.helperTextColor,
      hoverBackgroundColor: props.hoverBackgroundColor,
      hoverBorderColor: props.hoverBorderColor,
      focusBackgroundColor: props.focusBackgroundColor,
      focusBorderColor: props.focusBorderColor,
      errorBackgroundColor: props.errorBackgroundColor,
      errorTextColor: props.errorTextColor,
      errorBorderColor: props.errorBorderColor,
      errorLabelColor: props.errorLabelColor,
      errorHelperTextColor: props.errorHelperTextColor,
      successBackgroundColor: props.successBackgroundColor,
      successTextColor: props.successTextColor,
      successBorderColor: props.successBorderColor,
      successLabelColor: props.successLabelColor,
      successHelperTextColor: props.successHelperTextColor,
      disabledBackgroundColor: props.disabledBackgroundColor,
      disabledTextColor: props.disabledTextColor,
      disabledBorderColor: props.disabledBorderColor,
      disabledLabelColor: props.disabledLabelColor,
    },

    // Interaction state
    disabled: props.disabled,
    error: props.error,
    success: props.success,
    isHovered: isHovered.value,
    isFocused: isFocused.value,

    // Layout
    size: props.size,
    fullWidth: props.fullWidth,
    multiline: props.multiline,

    // Content
    label: props.label,
    helperText: props.helperText,

    // ARIA
    required: props.required,
    ariaLabel: props.ariaLabel,
    ariaDescribedby: props.ariaDescribedby,

    // Styles
    userStyles: props.style,

    // Dev mode
    showQualityWarnings: props.showQualityWarnings,
    customClass: props.class,
  });
});

// ============================================================================
// QUALITY WARNINGS (DEV MODE)
// ============================================================================

// Watch for quality warnings and log them
watch(
  () => textFieldOutput.value.qualityWarnings,
  (warnings) => {
    if (warnings.length > 0) {
      warnings.forEach((warning) => {
        console.warn(`[TextField] ${warning.message}`, warning.details);
      });
    }
  },
  { immediate: true }
);

// ============================================================================
// COMPUTED STYLES
// ============================================================================

const containerStyles = computed(() => ({
  width: textFieldOutput.value.styles.containerWidth,
  display: textFieldOutput.value.styles.containerDisplay,
  flexDirection: textFieldOutput.value.styles.containerFlexDirection,
  gap: `${textFieldOutput.value.styles.containerGap}px`,
}));

const inputStyles = computed(() => ({
  height: props.multiline ? 'auto' : `${textFieldOutput.value.styles.inputHeight}px`,
  paddingLeft: `${textFieldOutput.value.styles.inputPaddingLeft}px`,
  paddingRight: `${textFieldOutput.value.styles.inputPaddingRight}px`,
  paddingTop: `${textFieldOutput.value.styles.inputPaddingTop}px`,
  paddingBottom: `${textFieldOutput.value.styles.inputPaddingBottom}px`,
  fontSize: `${textFieldOutput.value.styles.inputFontSize}px`,
  fontWeight: textFieldOutput.value.styles.inputFontWeight,
  lineHeight: textFieldOutput.value.styles.inputLineHeight,
  fontFamily: textFieldOutput.value.styles.inputFontFamily,
  backgroundColor: textFieldOutput.value.styles.inputBackgroundColor,
  color: textFieldOutput.value.styles.inputColor,
  borderRadius: `${textFieldOutput.value.styles.inputBorderRadius}px`,
  outline: textFieldOutput.value.styles.inputOutline,
  cursor: textFieldOutput.value.styles.inputCursor,
  transition: textFieldOutput.value.styles.inputTransition,
  borderWidth: textFieldOutput.value.styles.inputBorderWidth ? `${textFieldOutput.value.styles.inputBorderWidth}px` : undefined,
  borderStyle: textFieldOutput.value.styles.inputBorderStyle,
  borderColor: textFieldOutput.value.styles.inputBorderColor,
}));

const labelStyles = computed(() => textFieldOutput.value.styles.labelColor ? {
  fontSize: `${textFieldOutput.value.styles.labelFontSize}px`,
  fontWeight: textFieldOutput.value.styles.labelFontWeight,
  color: textFieldOutput.value.styles.labelColor,
  marginBottom: `${textFieldOutput.value.styles.labelMarginBottom}px`,
} : undefined);

const helperStyles = computed(() => textFieldOutput.value.styles.helperColor ? {
  fontSize: `${textFieldOutput.value.styles.helperFontSize}px`,
  color: textFieldOutput.value.styles.helperColor,
  marginTop: `${textFieldOutput.value.styles.helperMarginTop}px`,
} : undefined);

// ============================================================================
// EVENT HANDLERS (Vue-specific)
// ============================================================================

const handleInput = (event: Event) => {
  if (props.disabled) {
    return;
  }
  const target = event.target as HTMLInputElement | HTMLTextAreaElement;
  emit('update:value', target.value);
};

const handleMouseEnter = () => {
  if (props.disabled) {
    return;
  }
  isHovered.value = true;
};

const handleMouseLeave = () => {
  isHovered.value = false;
};

const handleFocus = (event: FocusEvent) => {
  if (props.disabled) {
    return;
  }
  isFocused.value = true;
  emit('focus', event);
};

const handleBlur = (event: FocusEvent) => {
  isFocused.value = false;
  emit('blur', event);
};
</script>

<!--
CONTRACT COMPLIANCE:

✅ Zero logic duplication
   - ALL logic delegated to TextFieldCore.processTextField()
   - Adapter is THIN wrapper

✅ 100% token-driven
   - All colors from EnrichedToken (via TextFieldCore)
   - NO local color calculations

✅ State management via framework
   - Uses Vue's ref() for interaction state
   - TextFieldCore handles state determination

✅ Framework-specific concerns only
   - Template rendering (Vue-specific)
   - Event handling (Vue events → TextFieldCore)
   - Reactivity (Vue computed)

✅ Identical behavior to React
   - Same TextFieldCore
   - Same tokens
   - Same output

PATTERN: Exact copy of Button.vue adapted for TextField
-->
